# Práctica de laboratorio — Limpieza y preprocesamiento programático de la **Encuesta COVID** con Python

En esta práctica trabajarás con un conjunto de datos real procedente del cuestionario **EncuestaCOVID.docx**.  
Tu trabajo **no** consiste en limpiar el fichero a mano en Excel, sino en hacerlo **exclusivamente con código Python** sobre tus **120 filas asignadas**.

## Idea general de la práctica

Debes trabajar **columna a columna** (o, cuando proceda, **grupo de columnas de una misma pregunta**) y hacer lo siguiente:

1. **Identificar** a qué pregunta del cuestionario corresponde cada columna.
2. **Analizar** el tipo de dato real que contiene esa columna.
3. **Detectar problemas**: valores faltantes, espacios, errores tipográficos, codificaciones inconsistentes, categorías redundantes, outliers, mezclas de texto y número, etc.
4. **Proponer y escribir código** que limpie la columna o el grupo de columnas.
5. **Justificar** cada decisión de limpieza.
6. **Construir** una versión limpia del dataset y una versión reducida para análisis/modelado.

## Técnicas que debes usar a lo largo de la práctica

A partir de las transparencias de preprocesamiento, debes aplicar muchas de estas técnicas cuando tengan sentido:

- detección de valores faltantes;
- eliminación o imputación justificada;
- detección de inconsistencias;
- normalización de categorías de texto;
- detección de duplicados;
- detección y tratamiento de outliers;
- creación de variables derivadas;
- codificación de variables categóricas;
- escalado/normalización;
- discretización;
- reducción de variables.

## Importante

- **No modifiques el archivo XLSX manualmente**.
- Mantén siempre una copia cruda: `df_raw`.
- Toda limpieza debe quedar reflejada en código.
- No sobrescribas una columna original sin haberla inspeccionado antes.
- Cuando crees una versión limpia, usa nombres como `*_clean`, `*_num`, `*_ord`, etc., o bien documenta claramente el reemplazo.

## Entregables

Al final deberás entregar, como mínimo:

1. Este notebook completado y ejecutado.
2. Un dataframe limpio `df_limpio`.
3. Un dataframe reducido `df_modelo` con aproximadamente **15 variables útiles**.
4. Una **tabla de auditoría** donde se vea, para cada columna original:
   - a qué pregunta pertenece,
   - qué problema(s) detectaste,
   - qué estrategia aplicaste,
   - qué columna(s) final(es) generaste.

# 0. Carga de librerías y selección de tus 120 filas

In [1]:
import re
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option('display.max_rows', None)
pd.set_option("display.max_colwidth", 120)

In [2]:
# Carpeta de trabajo
carpeta = "/home/miguel/Desktop/uma-25-26-2/AC1/Practica1"
print("Carpeta de trabajo:", carpeta)

# Descarga en esta carpeta, desde el Campus Virtual, al menos estos ficheros:
# - DatosEncuestaCOVID.xlsx
# - EncuestaCOVID.docx
# - CodigosEstudiantado2025-2026.txt

Carpeta de trabajo: /home/miguel/Desktop/uma-25-26-2/AC1/Practica1

In [2]:
codigo = 40  # TODO: sustituye 69 por tu código de estudiante

inicio = 1 + (codigo - 1) * 120
fin = 120 + (codigo - 1) * 120

print(f"Tus filas van desde {inicio} hasta {fin}")

Tus filas van desde 4681 hasta 4800

In [3]:
df_raw = pd.read_excel("DatosEncuestaCOVID.xlsx")
print("Número total de filas del XLSX:", len(df_raw))

df = df_raw.iloc[inicio - 1 : fin].copy()
print("Número de filas de tu subconjunto:", len(df))

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

# 1. Exploración inicial obligatoria

**Antes de limpiar nada**, responde con código a estas preguntas:

- ¿Cuántas filas tiene tu subconjunto?
- ¿Cuántas columnas tiene?
- ¿Qué tipos de datos detecta pandas?
- ¿Qué columnas parecen numéricas pero no lo son?
- ¿Qué columnas parecen categóricas?
- ¿Qué columnas pertenecen a preguntas multirrespuesta?
- ¿Hay alguna discrepancia entre el número de columnas esperado y el número de columnas real?

In [5]:
print(f"El dataset tiene {df.shape[0]} filas y {df.shape[1]} columnas.")

El dataset tiene 120 filas y 153 columnas.

In [6]:
df.info()
df.head()
print(f"El dataset presenta datos de tipo float, object y string.")
print(f"Columnas como 'Convivencia-antes_1' parece numérica pero no lo es.")
print(f"Columnas como el 'Sexo_1' son categóricas.")
print(f"Columnas como el 'Transporte' son multirespuesta.")
print(f"En principio solo eran 53 preguntas, por lo que debería haber 53 columnas pero nos encontramos con 153 columnas.")

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 4680 to 4799
Columns: 153 entries, 1.CPBARRIO-ANTES_1 to 51.COVID-ANTICUERPOS_1
dtypes: float64(5), object(7), str(141)
memory usage: 143.6+ KB
El dataset presenta datos de tipo float, object y string.
Columnas como 'Convivencia-antes_1' parece numérica pero no lo es.
Columnas como el 'Sexo_1' son categóricas.
Columnas como el 'Transporte' son multirespuesta.
En principio solo eran 53 preguntas, por lo que debería haber 53 columnas pero nos encontramos con 153 columnas.

In [7]:
df.columns

Index(['1.CPBARRIO-ANTES_1', '1.CPBARRIO-ANTES_2', '2.SEXO_1', '3.EDAD_1',
       '4.PESO_1', '5TALLA_1', '6.DOMICILIO-ANTES_1', '7.AFLUENCIA-ANTES_1',
       '8.CONVIVENCIA-ANTES_1', '9.ED,DES-,NTES_1',
       ...
       '47.VACUNAS_5', '47.VACUNAS_6', '47.VACUNAS_7', '47.VACUNAS_8',
       '47.VACUNAS_9', '47.VACUNAS_10', '48.COVID-CONTACTO_1',
       '49.COVID-SOSPECHA_1', '50.COVID-PCR_1', '51.COVID-ANTICUERPOS_1'],
      dtype='str', length=153)

# 2. Funciones auxiliares para la auditoría

Las siguientes funciones **no resuelven** la práctica, pero te ayudan a inspeccionar el dataset de forma sistemática.

Úsalas tantas veces como necesites.

In [34]:
def resumen_columna(df, col, top=15):
    s = df[col]
    out = pd.DataFrame({
        "columna": [col],
        "dtype": [s.dtype],
        "n": [len(s)],
        "n_missing": [s.isna().sum()],
        "pct_missing": [100 * s.isna().mean()],
        "n_unicos": [s.nunique(dropna=True)]
    })
    display(out)
    print("\nPrimeros valores no nulos:")
    display(s.dropna().astype(str).head(top))
    print("\nFrecuencias (incluyendo NA):")
    display(s.astype("object").value_counts(dropna=False).head(top))


def ver_numerica(df, col, bins=20):
    s = pd.to_numeric(df[col], errors="coerce")
    display(s.describe())
    fig, ax = plt.subplots(1, 2, figsize=(12, 4))
    s.plot(kind="hist", bins=bins, ax=ax[0], title=f"Histograma: {col}")
    s.plot(kind="box", ax=ax[1], title=f"Boxplot: {col}")
    plt.tight_layout()
    plt.show()


def ver_categorica(df, col, top=20):
    s = df[col].astype("object")
    display(s.value_counts(dropna=False).head(top))


def columnas_con_prefijo(df, pregunta):
    pregunta = str(pregunta)
    patron = rf"^{re.escape(pregunta)}(?:\.|_|[A-Z])"
    return [c for c in df.columns if re.search(patron, c)]


def columnas_por_bloque(df, preguntas):
    cols = []
    for p in preguntas:
        cols.extend(columnas_con_prefijo(df, p))
    # preserva el orden original del dataframe
    cols = [c for c in df.columns if c in cols]
    return cols

# 3. Normalización inicial de valores faltantes y espacios

Antes de estudiar cada columna, crea una copia de trabajo y **normaliza representaciones obvias** de datos faltantes.

No conviertas todavía a número ni recodifiques categorías complejas: primero deja homogéneo el dataset.

In [9]:
df_trabajo = df.copy()

# TODO:
# 1) Convierte strings vacíos y espacios a NaN.
# 2) Busca otras representaciones de faltantes: "NA", "N/A", "No consta", "-", etc.
# 3) Decide cuáles debes convertir a NaN y cuáles no.
#
# Ejemplo orientativo:
# df_trabajo = df_trabajo.replace(r"^\s*$", np.nan, regex=True)

df_trabajo = df_trabajo.replace([r"^\s*$", "-", "No sé, no me consta", "No se, no me consta", ",", "NA", "N/A"], np.nan, regex=True)
df_trabajo.head()

,1.CPBARRIO-ANTES_1,1.CPBARRIO-ANTES_2,2.SEXO_1,3.EDAD_1,4.PESO_1,5TALLA_1,6.DOMICILIO-ANTES_1,7.AFLUENCIA-ANTES_1,8.CONVIVENCIA-ANTES_1,"9.ED,DES-,NTES_1",10.PROFESION-ANTES_1,11.LUGARTRABAJO-ANTES_1,12.OCIO_1,13.TRANSPORTE_1,13.TRANSPORTE_2,13.TRANSPORTE_3,13.TRANSPORTE_4,13.TRANSPORTE_5,13.TRANSPORTE_6,13.TRANSPORTE_7,14.EXTRANJERO_1,15.DESPLAZAMIENTO-NACIONAL_1,16.CPBARRIO-DURANTE_1,16.CPBARRIO-DURANTE_2,17.DOMICILIO-DURANTE_1,18.AFLUENCIA-DURANTE_1,19.CONVIVENCIA-DURANTE_1,20.EDADES-DURANTE_1,21.MASCOTAS_1,21.MASCOTAS_2,21.MASCOTAS_3,21.MASCOTAS_4,21.MASCOTAS_5,22.PROFESION-DURANTE_1,22.PROFESION-DURANTE_2,22.PROFESION-DURANTE_3,22.PROFESION-DURANTE_4,22.PROFESION-DURANTE_5,22.PROFESION-DURANTE_6,22.PROFESION-DURANTE_7,22.PROFESION-DURANTE_8,22.PROFESION-DURANTE_9,22.PROFESION-DURANTE_10,22.PROFESION-DURANTE_11,22.PROFESION-DURANTE_12,23.LUGARTRABAJO-DURANTE_1,24.SEGURIDAD-MES_1,24.SEGURIDAD-MES_2,24.SEGURIDAD-MES_3,24.SEGURIDAD-MES_4,25.SEGURIDAD-FRECUENCIA_1,25.SEGURIDAD-FRECUENCIA_2,25.SEGURIDAD-FRECUENCIA_3,25.SEGURIDAD-FRECUENCIA_4,25.SEGURIDAD-FRECUENCIA_5,26.FUMADOR_1,27.ALCOHOL_1,28.BEBIDAS_1,28.BEBIDAS_2,28.BEBIDAS_3,28.BEBIDAS_4,28.BEBIDAS_5,28.BEBIDAS_6,29.ANTIDEPRESIVOS_1,30.TRANQUILIZANTES_1,31.TRATAMIENTO-DOLOR_1,32.SUPLEMENTOS_1,32.SUPLEMENTOS_2,32.SUPLEMENTOS_3,33.ESTADO-SALUD_1,34.ENF-METABOLICA_1,34.ENF-METABOLICA_2,34.ENF-METABOLICA_3,34.ENF-METABOLICA_4,34.ENF-METABOLICA_5,34.ENF-METABOLICA_6,34.ENF-METABOLICA_7,34.ENF-METABOLICA_8,34.ENF-METABOLICA_9,35.ENF-AUTOINMUNE_1,35.ENF-AUTOINMUNE_2,35.ENF-AUTOINMUNE_3,35.ENF-AUTOINMUNE_4,35.ENF-AUTOINMUNE_5,35.ENF-AUTOINMUNE_6,35.ENF-AUTOINMUNE_7,35.ENF-AUTOINMUNE_8,36.ENF-ALERGIA_1,36.ENF-ALERGIA_2,36.ENF-ALERGIA_3,36.ENF-ALERGIA_4,36.ENF-ALERGIA_5,36.ENF-ALERGIA_6,36.ENF-ALERGIA_7,37.ENF-RESPIRATORIA_1,37.ENF-RESPIRATORIA_2,37.ENF-RESPIRATORIA_3,37.ENF-RESPIRATORIA_4,37.ENF-RESPIRATORIA_5,37.ENF-RESPIRATORIA_6,37.ENF-RESPIRATORIA_7,38.ENF-CARDIACA_1,38.ENF-CARDIACA_2,38.ENF-CARDIACA_3,38.ENF-CARDIACA_4,38.ENF-CARDIACA_5,38.ENF-CARDIACA_6,39.ENF-OTRAS_1,39.ENF-OTRAS_2,39.ENF-OTRAS_3,39.ENF-OTRAS_4,39.ENF-OTRAS_5,39.ENF-OTRAS_6,39.ENF-OTRAS_7,40.EPOC-RIESGO_1,40.EPOC-RIESGO_2,41.SALUD-TRIMESTRE_1,42.HOSPITAL-INGRESO_1,43.HOSPITAL-PRUEBAS_1,44.PATOLOGIA-CONSIS_1,45.PATOLOGIA-SINASIS_1,46.SINTOMATOLOGIA_1,46.SINTOMATOLOGIA_2,46.SINTOMATOLOGIA_3,46.SINTOMATOLOGIA_4,46.SINTOMATOLOGIA_5,46.SINTOMATOLOGIA_6,46.SINTOMATOLOGIA_7,46.SINTOMATOLOGIA_8,46.SINTOMATOLOGIA_9,46.SINTOMATOLOGIA_10,46.SINTOMATOLOGIA_11,46.SINTOMATOLOGIA_12,46.SINTOMATOLOGIA_13,46.SINTOMATOLOGIA_14,46.SINTOMATOLOGIA_15,46.SINTOMATOLOGIA_16,46.SINTOMATOLOGIA_17,46.SINTOMATOLOGIA_18,47.VACUNAS_1,47.VACUNAS_2,47.VACUNAS_3,47.VACUNAS_4,47.VACUNAS_5,47.VACUNAS_6,47.VACUNAS_7,47.VACUNAS_8,47.VACUNAS_9,47.VACUNAS_10,48.COVID-CONTACTO_1,49.COVID-SOSPECHA_1,50.COVID-PCR_1,51.COVID-ANTICUERPOS_1
4680,14005,14005,Hombre:,42,72.0,167,Piso en bloque de menos 50 viviendas,NaN,0,0,Ámbito educativo,Instituto de Enseñanza Secundaria,En lugares abiertos y cerrados por igual,Frecuente,Baja,Baja,Muy baja,Baja,NaN,Frecuente,NO,NaN,14005.0,Ciudad Jardín,Piso en bloque de más de 50 viviendas,NaN,0,0,Gato,NaN,NaN,NaN,NaN,NaN,Mediante teletrabajo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,En el hogar (teletrabajo/en paro/ tareas domésticas/confinado),Marzo,NaN,NaN,NaN,Frecuentemente,Algunas veces,Muy frecuentemente,Frecuentemente,Muy frecuentemente,No,NaN,Habitualmente,Habitualmente,De vez en cuando,No consumo,NaN,NaN,No,No,No,De vez en cuando,Habitualmente,Habitualmente,Excelente,No,No,No,Si,No,No,No,NaN,NaN,No,No,No,No,No,No,NaN,NaN,No,No,No,No,No,No,NaN,No,No,Si,No,No,NaN,NaN,No,No,No,No,NaN,NaN,No,No,Si,No,No,NaN,NaN,No,No,Excelente,No,No,NaN,No,No,No,Si,No,Si,No,No,No,No,No,No,No,No,No,Si,No,No,NaN,Si,No,NaN,NaN,NaN,NaN,NaN,No,No,NaN,No,No,No,no
4681,28002,Prosperidad,Mujer:,56,65.0,167,Piso en bloque de menos 50 viviendas,Medio (movimiento de residentes),0,NaN,Medios de comunicación,NaN,NaN,NaN,NaN,Baja,Baja,Frecuente,Baja,Frecuente,No,No he salido de mi comunidad,28002.0,Prosperidad,Piso en bloque de menos 50 viviendas,Medio (movimiento de residentes),0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,De forma presencial,NaN,NaN,Marzo,NaN,NaN,NaN,Frecuentemente,Algunas veces,Muy frecuentemente,Algunas veces,Algunas veces,No,NaN,Habitualmente,No consumo,Habitualmente,No consumo,NaN,NaN,No,No,No,De vez en cuando,Habitualmente,De vez en cuando,Bueno,No,No,No,Si,No,No,Si,NaN,NaN,No,No,No,No,No,No,NaN,NaN,Si,No,No,No,NaN,NaN,NaN,No,Si,Si,No,No,NaN,NaN,No,No,No,No,NaN,NaN,No,No,No,No,No,NaN,NaN,No,No,Regular,No,Sí,NaN,NaN,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NaN,No,NaN,No,Si,Si,No,No,No,No,NaN,No,No,No,no
4682,29006,Cruz Humilladero ( Málaga),Mujer:,33,88.0,167,Piso en bloque de menos 50 viviendas,NaN,0,NaN,Ámbito del ocio y la restauración,NaN,En lugares abiertos y cerrados por igual,Frecuente,Nula,Media,Frecuente,Media,NaN,Nula,NO,Córdoba,29006.0,Cruz Humilladero ( Málaga),Piso en bloque de menos 50 viviendas,Medio (movimiento de residentes),0,NaN,Otras mascotas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Despedido/a,NaN,NaN,NaN,NaN,NaN,En el hogar (teletrabajo/en paro/ tareas domésticas/confinado),Febrero,NaN,NaN,NaN,Muy frecuentemente,Muy frecuentemente,Muy frecuentemente,Frecuentemente,Algunas veces,Fumador social (o solo ocasionalmente),NaN,Habitualmente,Habitualmente,Habitualmente,No consumo,NaN,NaN,No,No,No,Habitualmente,Habitualmente,Habitualmente,Regular,No,No,No,No,Si,No,No,NaN,NaN,NaN,No,NaN,No,No,NaN,NaN,NaN,Si,Si,No,Si,Si,No,NaN,Si,Si,No,Si,NaN,NaN,NaN,No,No,No,NaN,NaN,NaN,NaN,No,No,NaN,NaN,NaN,NaN,No,No,Regular,No,Sí,NaN,NaN,Si,No,Si,Si,No,No,No,Si,No,Si,No,No,No,Si,Si,Si,Si,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,No,no
4683,38204,Casco histórico,Mujer:,65,58.0,167,Piso en bloque de menos 50 viviendas,NaN,0,0,Ámbito educativo,Jubilada desde 2018,En lugares abiertos y cerrados por igual,NaN,NaN,NaN,NaN,NaN,NaN,Frecuente,no,No he salido de mi comunidad,38204.0,casco bistorico,Piso en bloque de menos 50 viviendas,NaN,0,0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,jubilada desde 2018,Marzo,NaN,NaN,NaN,Muy frecuentemente,Nunca,Muy frecuentemente,Muy frecuentemente,Frecuentemente,NaN,NaN,Habitualmente,De vez en cuando,No consumo,No consumo,NaN,NaN,No,No,No,Habitualmente,Habitualmente,Habitualmente,Regular,No,No,No,Si,No,No,No,NaN,NaN,No,No,No,No,No,No,NaN,NaN,No,No,No,No,Si,No,NaN,No,Si,Si,Si,No,NaN,NaN,No,No,No,Si,NaN,NaN,No,No,No,No,No,NaN,NaN,Si,No,Bueno,No,No,No,No,No,Si,No,No,No,No,No,No,No,No,No,No,Si,No,No,No,No,NaN,NaN,No,No,No,No,No,No,No,No,NaN,No,No,No,no
4684,38201,La Laguna Centro,Mujer:,63,59.0,167,Piso en bloque de menos 50 viviendas,NaN,0,0,Ámbito administrativo,NaN,En lugares abiertos y cerrados por igual,Nula,Nula,Baja,Frecuente,Frecuente,Nula,Nula,no,No he salido de mi comunidad,38201.0,La Laguna Centro,Piso en bloque de menos 50 viviendas,Bajo (apenas tránsito de personas y/o vehículos),0,0,Perro,NaN,NaN,NaN,NaN,NaN,NaN,Mediante teletrabajo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,En el hogar (teletrabajo/en paro/ tareas domésticas/confinado),Marzo,NaN,NaN,NaN,Muy frecuentemente,Frecuentemente,Frecuentemente,Frecuentemente,Frecuentemente,NaN,No,Habitualmente,De vez en cuando,De vez en cuando,No consumo,NaN,NaN,No,No,No,Nunca,De vez en cuando,De vez en cuando,Bueno,No,No,No,No,No,No,No,NaN,NaN,No,No,No,No,No,No,NaN,NaN,Si,NaN,NaN,NaN,NaN,NaN,NaN,No,Si,No,No,No,NaN,NaN,No,No,No,No,NaN,NaN,No,No,No,Si,No,NaN,NaN,No,No,Bueno,No,No,No,No,No,No,No,Si,No,No,No,No,No,No,No,No,No,No,No,No,No,NaN,Si,No,No,No,No,No,No,No,No,NaN,No,NaN,No,no

In [10]:
# TODO: crea una tabla rápida con número y porcentaje de faltantes por columna
# missing = ...
# display(missing.head(30))

missing = pd.DataFrame({
    "nulos" : df_trabajo.isnull().sum(),
    "porcentaje" : (df_trabajo.isnull().sum() / len(df_trabajo)) * 100
})

display(missing.head(30))

                              nulos  porcentaje
1.CPBARRIO-ANTES_1                1    0.833333
1.CPBARRIO-ANTES_2               12   10.000000
2.SEXO_1                          1    0.833333
3.EDAD_1                          0    0.000000
4.PESO_1                          0    0.000000
5TALLA_1                          0    0.000000
6.DOMICILIO-ANTES_1               0    0.000000
7.AFLUENCIA-ANTES_1              41   34.166667
8.CONVIVENCIA-ANTES_1             0    0.000000
9.ED,DES-,NTES_1                 80   66.666667
10.PROFESION-ANTES_1              8    6.666667
11.LUGARTRABAJO-ANTES_1          92   76.666667
12.OCIO_1                        46   38.333333
13.TRANSPORTE_1                  12   10.000000
13.TRANSPORTE_2                  33   27.500000
13.TRANSPORTE_3                  38   31.666667
13.TRANSPORTE_4                  33   27.500000
13.TRANSPORTE_5                  31   25.833333
13.TRANSPORTE_6                  36   30.000000
13.TRANSPORTE_7                  17   14.166667
14.EXTRANJERO_1                   6    5.000000
15.DESPLAZAMIENTO-NACIONAL_1     46   38.333333
16.CPBARRIO-DURANTE_1             4    3.333333
16.CPBARRIO-DURANTE_2            14   11.666667
17.DOMICILIO-DURANTE_1            3    2.500000
18.AFLUENCIA-DURANTE_1           22   18.333333
19.CONVIVENCIA-DURANTE_1          3    2.500000
20.EDADES-DURANTE_1              68   56.666667
21.MASCOTAS_1                     7    5.833333
21.MASCOTAS_2                   120  100.000000

# 4. Diccionario del cuestionario y tabla maestra de auditoría

En el fichero **EncuestaCOVID.docx** aparecen las preguntas del cuestionario.  
A continuación tienes un **diccionario de preguntas** resumido para ayudarte a relacionar cada columna del XLSX con la pregunta correspondiente.

**Tu tarea no es editar este diccionario**, sino usarlo para construir una auditoría **columna a columna**.

In [11]:
diccionario_preguntas = pd.DataFrame([('P1', '1', 'Código postal antes del confinamiento', 'texto/código', 'longitud, dígitos, ceros a la izquierda, faltantes'), ('P1', '1.1', 'Barrio antes del confinamiento', 'texto nominal', 'espacios, mayúsculas, tildes, abreviaturas, duplicados semánticos'), ('P1', '2', 'Sexo', 'categórica nominal', 'H/M, Hombre/Mujer, mayúsculas, categorías extrañas'), ('P1', '3', 'Edad', 'numérica', 'conversión a número, valores imposibles, outliers, imputación'), ('P1', '4', 'Peso (kg)', 'numérica', 'conversión a número, unidades, extremos, ceros/imposibles'), ('P1', '5', 'Talla (cm)', 'numérica', 'conversión a número, cm frente a m, extremos, ceros/imposibles'), ('P1', '6', 'Tipo de domicilio antes', 'categórica nominal', 'unificar categorías, otros, faltantes'), ('P1', '7', 'Afluencia en la zona antes', 'categórica ordinal', 'bajo/medio/alto, orden lógico, variantes de texto'), ('P1', '8', 'Número de convivientes antes', 'numérica discreta', 'enteros, negativos, extremos, faltantes'), ('P1', '9', 'Edades de convivientes antes', 'texto/lista', 'listas mal formadas, separadores, extracción de resúmenes'), ('P1', '10', 'Ámbito profesional antes', 'categórica nominal', 'sinónimos, otros, categorías mezcladas'), ('P1', '11', 'Descripción del lugar de trabajo antes', 'categórica nominal', 'unificación y categorías raras'), ('P1', '12', 'Tiempo libre antes', 'categórica nominal', "unificación y categoría 'Otro'"), ('P1', '13', 'Medio de transporte habitual antes', 'tabla/orden de preferencias', 'listas, separadores, categorías redundantes'), ('P1', '14', 'Viaje al extranjero', 'mixta sí/no + texto', 'separar indicador y destino, faltantes'), ('P1', '15', 'Desplazamiento dentro de España', 'categórica nominal', 'sí/no/madrid/barcelona/otra/otro'), ('P2', '16', 'Código postal durante el confinamiento', 'texto/código', 'igual que P1.1'), ('P2', '16.1', 'Barrio durante el confinamiento', 'texto nominal', 'igual que P1.1'), ('P2', '17', 'Tipo de domicilio durante', 'categórica nominal', 'comparar con P1.6'), ('P2', '18', 'Afluencia en la zona durante', 'categórica ordinal', 'comparar con P1.7'), ('P2', '19', 'Número de convivientes durante', 'numérica discreta', 'enteros, extremos, comparación con P1.8'), ('P2', '20', 'Edades de convivientes durante', 'texto/lista', 'parseo, resúmenes, consistencia con P2.19'), ('P2', '21', 'Convivencia con mascotas', 'multirrespuesta / nominal', 'no/perro/gato/otras; consistencia entre marcas'), ('P2', '22', 'Ámbito y forma de ejercer la profesión durante', 'tabla multirrespuesta', 'una respuesta por fila, categorías válidas'), ('P2', '23', 'Descripción del lugar de trabajo durante', 'categórica nominal', 'unificación y coherencia'), ('P2', '24', 'Mes de inicio de medidas de seguridad', 'categórica ordinal', 'enero-febrero-marzo-abril-otro'), ('P2', '25', 'Frecuencia de medidas de seguridad', 'tabla ordinal multicolumna', 'ordinalidad y coherencia por medida'), ('P3', '26', 'Tabaquismo', 'categórica mixta', 'orden parcial, fumador social/pasivo/vapeo/otro'), ('P3', '27', 'Consumo de alcohol', 'categórica nominal/ordinal', 'no/puntual/habitual/otro'), ('P3', '28', 'Bebidas estimulantes', 'tabla ordinal multicolumna', 'nunca/ocasional/frecuente'), ('P3', '29', 'Antidepresivos', 'categórica nominal', 'sí/no/otro; posible texto libre'), ('P3', '30', 'Tranquilizantes', 'categórica nominal', 'sí/no/otro; posible texto libre'), ('P3', '31', 'Tratamiento crónico para el dolor', 'categórica nominal', 'sí/no/otro; posible texto libre'), ('P3', '32', 'Consumo habitual de productos', 'tabla ordinal multicolumna', 'nunca/de vez en cuando/habitualmente'), ('P3', '33', 'Estado de salud general', 'categórica ordinal', 'excelente/bueno/regular/malo/...'), ('P3', '34', 'Enfermedades metabólicas', 'multicolumna ternaria', 'sí/no/no sé por enfermedad'), ('P3', '35', 'Trastornos autoinmunes', 'multicolumna ternaria', 'sí/no/no sé por enfermedad'), ('P3', '36', 'Alergias', 'multicolumna ternaria', 'sí/no/no sé por alergia'), ('P3', '37', 'Enfermedades respiratorias', 'multicolumna ternaria', 'sí/no/no sé por enfermedad'), ('P3', '38', 'Enfermedades cardíacas', 'multicolumna ternaria', 'sí/no/no sé por enfermedad'), ('P3', '39', 'Patologías en los últimos 2 años', 'multicolumna ternaria', 'sí/no/no sé por patología'), ('P3', '40', 'EPOC', 'categórica binaria', 'sí/no, faltantes'), ('P3', '40.1', 'Condiciones de riesgo', 'multirrespuesta', 'cáncer, trasplante, embarazo, no, otro'), ('P4', '41', 'Estado de salud últimos meses', 'categórica ordinal', 'excelente/bueno/regular/malo/otro'), ('P4', '42', 'Patología con ingreso hospitalario', 'categórica nominal', 'sí/no/otro + posible texto'), ('P4', '43', 'Visita a centro hospitalario', 'categórica binaria', 'sí/no'), ('P4', '44', 'Otra patología con asistencia médica', 'categórica nominal', 'sí/no/otro'), ('P4', '45', 'Otra patología sin asistencia médica', 'categórica nominal', 'sí/no/otro'), ('P4', '46', 'Sintomatología reciente', 'multicolumna binaria', 'sí/no por síntoma, consistencia'), ('P5', '47', 'Vacunas y enfermedades previas', 'multicolumna ternaria', 'sí/no/no sé por vacuna/enfermedad'), ('P5', '48', 'Convivencia con positivo COVID', 'categórica nominal', 'sí/no/no sé/otro'), ('P5', '49', 'Sospecha de COVID', 'categórica nominal', 'sí/no/no sé/otro'), ('P5', '50', 'Prueba PCR', 'categórica nominal', 'no/espera/positivo/negativo/otro'), ('P5', '51', 'Test de anticuerpos', 'categórica nominal', 'sí con anticuerpos/sí sin anticuerpos/no/otro')],
    columns=["bloque", "pregunta", "descripcion", "tipo_sugerido", "foco_limpieza"])

display(diccionario_preguntas)

,bloque,pregunta,descripcion,tipo_sugerido,foco_limpieza
0,P1,1,Código postal antes del confinamiento,texto/código,"longitud, dígitos, ceros a la izquierda, faltantes"
1,P1,1.1,Barrio antes del confinamiento,texto nominal,"espacios, mayúsculas, tildes, abreviaturas, duplicados semánticos"
2,P1,2,Sexo,categórica nominal,"H/M, Hombre/Mujer, mayúsculas, categorías extrañas"
3,P1,3,Edad,numérica,"conversión a número, valores imposibles, outliers, imputación"
4,P1,4,Peso (kg),numérica,"conversión a número, unidades, extremos, ceros/imposibles"
5,P1,5,Talla (cm),numérica,"conversión a número, cm frente a m, extremos, ceros/imposibles"
6,P1,6,Tipo de domicilio antes,categórica nominal,"unificar categorías, otros, faltantes"
7,P1,7,Afluencia en la zona antes,categórica ordinal,"bajo/medio/alto, orden lógico, variantes de texto"
8,P1,8,Número de convivientes antes,numérica discreta,"enteros, negativos, extremos, faltantes"
9,P1,9,Edades de convivientes antes,texto/lista,"listas mal formadas, separadores, extracción de resúmenes"
10,P1,10,Ámbito profesional antes,categórica nominal,"sinónimos, otros, categorías mezcladas"
11,P1,11,Descripción del lugar de trabajo antes,categórica nominal,unificación y categorías raras
12,P1,12,Tiempo libre antes,categórica nominal,unificación y categoría 'Otro'
13,P1,13,Medio de transporte habitual antes,tabla/orden de preferencias,"listas, separadores, categorías redundantes"
14,P1,14,Viaje al extranjero,mixta sí/no + texto,"separar indicador y destino, faltantes"
15,P1,15,Desplazamiento dentro de España,categórica nominal,sí/no/madrid/barcelona/otra/otro
16,P2,16,Código postal durante el confinamiento,texto/código,igual que P1.1
17,P2,16.1,Barrio durante el confinamiento,texto nominal,igual que P1.1
18,P2,17,Tipo de domicilio durante,categórica nominal,comparar con P1.6
19,P2,18,Afluencia en la zona durante,categórica ordinal,comparar con P1.7
20,P2,19,Número de convivientes durante,numérica discreta,"enteros, extremos, comparación con P1.8"
21,P2,20,Edades de convivientes durante,texto/lista,"parseo, resúmenes, consistencia con P2.19"
22,P2,21,Convivencia con mascotas,multirrespuesta / nominal,no/perro/gato/otras; consistencia entre marcas
23,P2,22,Ámbito y forma de ejercer la profesión durante,tabla multirrespuesta,"una respuesta por fila, categorías válidas"
24,P2,23,Descripción del lugar de trabajo durante,categórica nominal,unificación y coherencia
25,P2,24,Mes de inicio de medidas de seguridad,categórica ordinal,enero-febrero-marzo-abril-otro
26,P2,25,Frecuencia de medidas de seguridad,tabla ordinal multicolumna,ordinalidad y coherencia por medida
27,P3,26,Tabaquismo,categórica mixta,"orden parcial, fumador social/pasivo/vapeo/otro"
28,P3,27,Consumo de alcohol,categórica nominal/ordinal,no/puntual/habitual/otro
29,P3,28,Bebidas estimulantes,tabla ordinal multicolumna,nunca/ocasional/frecuente
30,P3,29,Antidepresivos,categórica nominal,sí/no/otro; posible texto libre
31,P3,30,Tranquilizantes,categórica nominal,sí/no/otro; posible texto libre
32,P3,31,Tratamiento crónico para el dolor,categórica nominal,sí/no/otro; posible texto libre
33,P3,32,Consumo habitual de productos,tabla ordinal multicolumna,nunca/de vez en cuando/habitualmente
34,P3,33,Estado de salud general,categórica ordinal,excelente/bueno/regular/malo/...
35,P3,34,Enfermedades metabólicas,multicolumna ternaria,sí/no/no sé por enfermedad
36,P3,35,Trastornos autoinmunes,multicolumna ternaria,sí/no/no sé por enfermedad
37,P3,36,Alergias,multicolumna ternaria,sí/no/no sé por alergia
38,P3,37,Enfermedades respiratorias,multicolumna ternaria,sí/no/no sé por enfermedad
39,P3,38,Enfermedades cardíacas,multicolumna ternaria,sí/no/no sé por enfermedad
40,P3,39,Patologías en los últimos 2 años,multicolumna ternaria,sí/no/no sé por patología
41,P3,40,EPOC,categórica binaria,"sí/no, faltantes"
42,P3,40.1,Condiciones de riesgo,multirrespuesta,"cáncer, trasplante, embarazo, no, otro"
43,P4,41,Estado de salud últimos meses,categórica ordinal,excelente/bueno/regular/malo/otro
44,P4,42,Patología con ingreso hospitalario,categórica nominal,sí/no/otro + posible texto
45,P4,43,Visita a centro hospitalario,categórica binaria,sí/no
46,P4,44,Otra patología con asistencia médica,categórica nominal,sí/no/otro
47,P4,45,Otra patología sin asistencia médica,categórica nominal,sí/no/otro
48,P4,46,Sintomatología reciente,multicolumna binaria,"sí/no por síntoma, consistencia"
49,P5,47,Vacunas y enfermedades previas,multicolumna ternaria,sí/no/no sé por vacuna/enfermedad
50,P5,48,Convivencia con positivo COVID,categórica nominal,sí/no/no sé/otro
51,P5,49,Sospecha de COVID,categórica nominal,sí/no/no sé/otro
52,P5,50,Prueba PCR,categórica nominal,no/espera/positivo/negativo/otro
53,P5,51,Test de anticuerpos,categórica nominal,sí con anticuerpos/sí sin anticuerpos/no/otro

## Construye ahora tu tabla maestra de auditoría

La idea es que tengas **una fila por columna real del XLSX**.  
Después, irás rellenando o ampliando esta tabla durante la práctica.

In [12]:
auditoria = pd.DataFrame({"columna_original": df_trabajo.columns})
auditoria["pregunta"] = auditoria["columna_original"].str.extract(r"^(\d+(?:\.\d+)?)")[0]
auditoria["dtype_raw"] = [df_trabajo[c].dtype for c in df_trabajo.columns]
auditoria["n_missing"] = [df_trabajo[c].isna().sum() for c in df_trabajo.columns]
auditoria["pct_missing"] = [100 * df_trabajo[c].isna().mean() for c in df_trabajo.columns]
auditoria["n_unicos"] = [df_trabajo[c].nunique(dropna=True) for c in df_trabajo.columns]

auditoria = auditoria.merge(diccionario_preguntas, on="pregunta", how="left")

# Columnas que debes completar tú, manualmente o con ayuda de código
auditoria["problemas_detectados"] = ""
auditoria["estrategia_aplicada"] = ""
auditoria["columnas_generadas"] = ""

display(auditoria.head(30))

,columna_original,pregunta,dtype_raw,n_missing,pct_missing,n_unicos,bloque,descripcion,tipo_sugerido,foco_limpieza,problemas_detectados,estrategia_aplicada,columnas_generadas
0,1.CPBARRIO-ANTES_1,1,object,1,0.833333,92,P1,Código postal antes del confinamiento,texto/código,"longitud, dígitos, ceros a la izquierda, faltantes",,,
1,1.CPBARRIO-ANTES_2,1,str,12,10.000000,97,P1,Código postal antes del confinamiento,texto/código,"longitud, dígitos, ceros a la izquierda, faltantes",,,
2,2.SEXO_1,2,str,1,0.833333,2,P1,Sexo,categórica nominal,"H/M, Hombre/Mujer, mayúsculas, categorías extrañas",,,
3,3.EDAD_1,3,object,0,0.000000,46,P1,Edad,numérica,"conversión a número, valores imposibles, outliers, imputación",,,
4,4.PESO_1,4,float64,0,0.000000,37,P1,Peso (kg),numérica,"conversión a número, unidades, extremos, ceros/imposibles",,,
5,5TALLA_1,5,object,0,0.000000,7,P1,Talla (cm),numérica,"conversión a número, cm frente a m, extremos, ceros/imposibles",,,
6,6.DOMICILIO-ANTES_1,6,str,0,0.000000,4,P1,Tipo de domicilio antes,categórica nominal,"unificar categorías, otros, faltantes",,,
7,7.AFLUENCIA-ANTES_1,7,str,41,34.166667,2,P1,Afluencia en la zona antes,categórica ordinal,"bajo/medio/alto, orden lógico, variantes de texto",,,
8,8.CONVIVENCIA-ANTES_1,8,object,0,0.000000,1,P1,Número de convivientes antes,numérica discreta,"enteros, negativos, extremos, faltantes",,,
9,"9.ED,DES-,NTES_1",9,object,80,66.666667,3,P1,Edades de convivientes antes,texto/lista,"listas mal formadas, separadores, extracción de resúmenes",,,
10,10.PROFESION-ANTES_1,10,str,8,6.666667,27,P1,Ámbito profesional antes,categórica nominal,"sinónimos, otros, categorías mezcladas",,,
11,11.LUGARTRABAJO-ANTES_1,11,str,92,76.666667,16,P1,Descripción del lugar de trabajo antes,categórica nominal,unificación y categorías raras,,,
12,12.OCIO_1,12,str,46,38.333333,3,P1,Tiempo libre antes,categórica nominal,unificación y categoría 'Otro',,,
13,13.TRANSPORTE_1,13,str,12,10.000000,5,P1,Medio de transporte habitual antes,tabla/orden de preferencias,"listas, separadores, categorías redundantes",,,
14,13.TRANSPORTE_2,13,str,33,27.500000,5,P1,Medio de transporte habitual antes,tabla/orden de preferencias,"listas, separadores, categorías redundantes",,,
15,13.TRANSPORTE_3,13,str,38,31.666667,4,P1,Medio de transporte habitual antes,tabla/orden de preferencias,"listas, separadores, categorías redundantes",,,
16,13.TRANSPORTE_4,13,str,33,27.500000,5,P1,Medio de transporte habitual antes,tabla/orden de preferencias,"listas, separadores, categorías redundantes",,,
17,13.TRANSPORTE_5,13,str,31,25.833333,5,P1,Medio de transporte habitual antes,tabla/orden de preferencias,"listas, separadores, categorías redundantes",,,
18,13.TRANSPORTE_6,13,str,36,30.000000,5,P1,Medio de transporte habitual antes,tabla/orden de preferencias,"listas, separadores, categorías redundantes",,,
19,13.TRANSPORTE_7,13,str,17,14.166667,5,P1,Medio de transporte habitual antes,tabla/orden de preferencias,"listas, separadores, categorías redundantes",,,
20,14.EXTRANJERO_1,14,str,6,5.000000,20,P1,Viaje al extranjero,mixta sí/no + texto,"separar indicador y destino, faltantes",,,
21,15.DESPLAZAMIENTO-NACIONAL_1,15,str,46,38.333333,3,P1,Desplazamiento dentro de España,categórica nominal,sí/no/madrid/barcelona/otra/otro,,,
22,16.CPBARRIO-DURANTE_1,16,float64,4,3.333333,89,P2,Código postal durante el confinamiento,texto/código,igual que P1.1,,,
23,16.CPBARRIO-DURANTE_2,16,str,14,11.666667,95,P2,Código postal durante el confinamiento,texto/código,igual que P1.1,,,
24,17.DOMICILIO-DURANTE_1,17,str,3,2.500000,4,P2,Tipo de domicilio durante,categórica nominal,comparar con P1.6,,,
25,18.AFLUENCIA-DURANTE_1,18,str,22,18.333333,2,P2,Afluencia en la zona durante,categórica ordinal,comparar con P1.7,,,
26,19.CONVIVENCIA-DURANTE_1,19,str,3,2.500000,8,P2,Número de convivientes durante,numérica discreta,"enteros, extremos, comparación con P1.8",,,
27,20.EDADES-DURANTE_1,20,object,68,56.666667,21,P2,Edades de convivientes durante,texto/lista,"parseo, resúmenes, consistencia con P2.19",,,
28,21.MASCOTAS_1,21,str,7,5.833333,4,P2,Convivencia con mascotas,multirrespuesta / nominal,no/perro/gato/otras; consistencia entre marcas,,,
29,21.MASCOTAS_2,21,str,120,100.000000,0,P2,Convivencia con mascotas,multirrespuesta / nominal,no/perro/gato/otras; consistencia entre marcas,,,

In [13]:
def registrar_auditoria(col, problema, accion, nueva):
    idx = auditoria[auditoria["columna_original"] == col].index[0]
    auditoria.at[idx, "problemas_detectados"] = problema
    auditoria.at[idx, "accion_realizada"] = accion
    auditoria.at[idx, "columna_nueva"] = nueva

# 5. Auditoría global del dataset

Antes de entrar en las preguntas, realiza una auditoría global.

## Tareas

1. Detecta posibles **duplicados exactos**.
2. Detecta valores con espacios iniciales/finales.
3. Busca valores sospechosos repetidos (`"Otro"`, `"No se"`, `"NS/NC"`, `"-"`, etc.).
4. Comprueba qué columnas parecen **numéricas pero están guardadas como texto**.
5. Señala qué columnas parecen:
   - nominales,
   - ordinales,
   - numéricas,
   - multirrespuesta,
   - texto libre.

In [14]:
# TODO: duplicados exactos
# duplicados = ...
# display(duplicados)

duplicados = df_trabajo[df_trabajo.duplicated(keep=False)]
display(duplicados)
print(f"Hay {len(duplicados) // 2} valores duplicados.")

,1.CPBARRIO-ANTES_1,1.CPBARRIO-ANTES_2,2.SEXO_1,3.EDAD_1,4.PESO_1,5TALLA_1,6.DOMICILIO-ANTES_1,7.AFLUENCIA-ANTES_1,8.CONVIVENCIA-ANTES_1,"9.ED,DES-,NTES_1",10.PROFESION-ANTES_1,11.LUGARTRABAJO-ANTES_1,12.OCIO_1,13.TRANSPORTE_1,13.TRANSPORTE_2,13.TRANSPORTE_3,13.TRANSPORTE_4,13.TRANSPORTE_5,13.TRANSPORTE_6,13.TRANSPORTE_7,14.EXTRANJERO_1,15.DESPLAZAMIENTO-NACIONAL_1,16.CPBARRIO-DURANTE_1,16.CPBARRIO-DURANTE_2,17.DOMICILIO-DURANTE_1,18.AFLUENCIA-DURANTE_1,19.CONVIVENCIA-DURANTE_1,20.EDADES-DURANTE_1,21.MASCOTAS_1,21.MASCOTAS_2,21.MASCOTAS_3,21.MASCOTAS_4,21.MASCOTAS_5,22.PROFESION-DURANTE_1,22.PROFESION-DURANTE_2,22.PROFESION-DURANTE_3,22.PROFESION-DURANTE_4,22.PROFESION-DURANTE_5,22.PROFESION-DURANTE_6,22.PROFESION-DURANTE_7,22.PROFESION-DURANTE_8,22.PROFESION-DURANTE_9,22.PROFESION-DURANTE_10,22.PROFESION-DURANTE_11,22.PROFESION-DURANTE_12,23.LUGARTRABAJO-DURANTE_1,24.SEGURIDAD-MES_1,24.SEGURIDAD-MES_2,24.SEGURIDAD-MES_3,24.SEGURIDAD-MES_4,25.SEGURIDAD-FRECUENCIA_1,25.SEGURIDAD-FRECUENCIA_2,25.SEGURIDAD-FRECUENCIA_3,25.SEGURIDAD-FRECUENCIA_4,25.SEGURIDAD-FRECUENCIA_5,26.FUMADOR_1,27.ALCOHOL_1,28.BEBIDAS_1,28.BEBIDAS_2,28.BEBIDAS_3,28.BEBIDAS_4,28.BEBIDAS_5,28.BEBIDAS_6,29.ANTIDEPRESIVOS_1,30.TRANQUILIZANTES_1,31.TRATAMIENTO-DOLOR_1,32.SUPLEMENTOS_1,32.SUPLEMENTOS_2,32.SUPLEMENTOS_3,33.ESTADO-SALUD_1,34.ENF-METABOLICA_1,34.ENF-METABOLICA_2,34.ENF-METABOLICA_3,34.ENF-METABOLICA_4,34.ENF-METABOLICA_5,34.ENF-METABOLICA_6,34.ENF-METABOLICA_7,34.ENF-METABOLICA_8,34.ENF-METABOLICA_9,35.ENF-AUTOINMUNE_1,35.ENF-AUTOINMUNE_2,35.ENF-AUTOINMUNE_3,35.ENF-AUTOINMUNE_4,35.ENF-AUTOINMUNE_5,35.ENF-AUTOINMUNE_6,35.ENF-AUTOINMUNE_7,35.ENF-AUTOINMUNE_8,36.ENF-ALERGIA_1,36.ENF-ALERGIA_2,36.ENF-ALERGIA_3,36.ENF-ALERGIA_4,36.ENF-ALERGIA_5,36.ENF-ALERGIA_6,36.ENF-ALERGIA_7,37.ENF-RESPIRATORIA_1,37.ENF-RESPIRATORIA_2,37.ENF-RESPIRATORIA_3,37.ENF-RESPIRATORIA_4,37.ENF-RESPIRATORIA_5,37.ENF-RESPIRATORIA_6,37.ENF-RESPIRATORIA_7,38.ENF-CARDIACA_1,38.ENF-CARDIACA_2,38.ENF-CARDIACA_3,38.ENF-CARDIACA_4,38.ENF-CARDIACA_5,38.ENF-CARDIACA_6,39.ENF-OTRAS_1,39.ENF-OTRAS_2,39.ENF-OTRAS_3,39.ENF-OTRAS_4,39.ENF-OTRAS_5,39.ENF-OTRAS_6,39.ENF-OTRAS_7,40.EPOC-RIESGO_1,40.EPOC-RIESGO_2,41.SALUD-TRIMESTRE_1,42.HOSPITAL-INGRESO_1,43.HOSPITAL-PRUEBAS_1,44.PATOLOGIA-CONSIS_1,45.PATOLOGIA-SINASIS_1,46.SINTOMATOLOGIA_1,46.SINTOMATOLOGIA_2,46.SINTOMATOLOGIA_3,46.SINTOMATOLOGIA_4,46.SINTOMATOLOGIA_5,46.SINTOMATOLOGIA_6,46.SINTOMATOLOGIA_7,46.SINTOMATOLOGIA_8,46.SINTOMATOLOGIA_9,46.SINTOMATOLOGIA_10,46.SINTOMATOLOGIA_11,46.SINTOMATOLOGIA_12,46.SINTOMATOLOGIA_13,46.SINTOMATOLOGIA_14,46.SINTOMATOLOGIA_15,46.SINTOMATOLOGIA_16,46.SINTOMATOLOGIA_17,46.SINTOMATOLOGIA_18,47.VACUNAS_1,47.VACUNAS_2,47.VACUNAS_3,47.VACUNAS_4,47.VACUNAS_5,47.VACUNAS_6,47.VACUNAS_7,47.VACUNAS_8,47.VACUNAS_9,47.VACUNAS_10,48.COVID-CONTACTO_1,49.COVID-SOSPECHA_1,50.COVID-PCR_1,51.COVID-ANTICUERPOS_1
4736,29011,Virreina,Mujer:,37,54.0,170,Piso en bloque de menos 50 viviendas,Medio (movimiento de residentes),0,NaN,Marketing,NaN,En lugares abiertos y cerrados por igual,Frecuente,Nula,Nula,Nula,Muy baja,Muy baja,Muy baja,No,No he salido de mi comunidad,29011.0,Virreina,Piso en bloque de menos 50 viviendas,Medio (movimiento de residentes),0,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,Mediante teletrabajo,Mediante teletrabajo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,En el hogar (teletrabajo/en paro/ tareas domésticas/confinado),Marzo,NaN,NaN,NaN,Muy frecuentemente,Algunas veces,Frecuentemente,Frecuentemente,Nunca,No,NaN,Habitualmente,No consumo,No consumo,No consumo,NaN,NaN,No,No,No,Nunca,De vez en cuando,Nunca,Bueno,No,No,No,No,No,No,No,NaN,NaN,No,No,No,No,No,No,NaN,NaN,NaN,NaN,No,Si,No,No,NaN,No,No,No,No,No,NaN,NaN,No,No,No,No,NaN,NaN,No,No,No,Si,No,NaN,NaN,No,No,Bueno,No,Sí,No,No,No,No,Si,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,No,no
4737,29011,Virreina,Mujer:,37,54.0,170,Piso en bloque de menos 50 viviendas,Medio (movimiento de residentes),0,NaN,Marketing,NaN,En lugares abiertos y cerrados por igual,Frecuente,Nula,Nula,Nula,Muy baja,Muy baja,Muy baja,No,No he salido de mi comunidad,29011.0,Virreina,Piso en bloque de menos 50 viviendas,Medio (movimiento de residentes),0,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,Mediante teletrabajo,Mediante teletrabajo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,En el hogar (teletrabajo/en paro/ tareas domésticas/confinado),Marzo,NaN,NaN,NaN,Muy frecuentemente,Algunas veces,Frecuentemente,Frecuentemente,Nunca,No,NaN,Habitualmente,No consumo,No consumo,No consumo,NaN,NaN,No,No,No,Nunca,De vez en cuando,Nunca,Bueno,No,No,No,No,No,No,No,NaN,NaN,No,No,No,No,No,No,NaN,NaN,NaN,NaN,No,Si,No,No,NaN,No,No,No,No,No,NaN,NaN,No,No,No,No,NaN,NaN,No,No,No,Si,No,NaN,NaN,No,No,Bueno,No,Sí,No,No,No,No,Si,No,No,No,No,No,No,No,No,No,No,No,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,No,no
4753,14500,Puente Genil,Mujer:,33,59.0,170,Piso en bloque de menos 50 viviendas,Medio (movimiento de residentes),0,NaN,Investigación y sanitario,NaN,En lugares abiertos y cerrados por igual,Frecuente,Nula,Muy baja,Muy baja,Nula,Muy baja,Frecuente,No,No he salido de mi comunidad,14500.0,Puente Genil,Piso en bloque de menos 50 viviendas,Medio (movimiento de residentes),0,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mediante teletrabajo,NaN,NaN,NaN,NaN,En el hogar (teletrabajo/en paro/ tareas domésticas/confinado),Marzo,NaN,NaN,NaN,Muy frecuentemente,Muy frecuentemente,Muy frecuentemente,Algunas veces,Muy frecuentemente,Fumador social (o solo ocasionalmente),NaN,Habitualmente,De vez en cuando,No consumo,No consumo,NaN,NaN,No,NaN,NaN,Nunca,Habitualmente,Habitualmente,Excelente,No,No,No,No,No,NaN,NaN,NaN,NaN,No,No,No,No,No,No,NaN,NaN,No,No,No,No,No,No,NaN,No,No,No,No,No,NaN,NaN,No,No,No,No,NaN,NaN,No,No,No,No,No,NaN,NaN,No,No,Bueno,No,Sí,No,No,Si,No,Si,Si,No,No,No,No,No,Si,No,No,No,Si,No,Si,No,NaN,Si,Si,Si,NaN,NaN,NaN,NaN,No,Si,NaN,No,No,No,no
4755,14500,Puente Genil,Mujer:,33,59.0,170,Piso en bloque de menos 50 viviendas,Medio (movimiento de residentes),0,NaN,Investigación y sanitario,NaN,En lugares abiertos y cerrados por igual,Frecuente,Nula,Muy baja,Muy baja,Nula,Muy baja,Frecuente,No,No he salido de mi comunidad,14500.0,Puente Genil,Piso en bloque de menos 50 viviendas,Medio (movimiento de residentes),0,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mediante teletrabajo,NaN,NaN,NaN,NaN,En el hogar (teletrabajo/en paro/ tareas domésticas/confinado),Marzo,NaN,NaN,NaN,Muy frecuentemente,Muy frecuentemente,Muy frecuentemente,Algunas veces,Muy frecuentemente,Fumador social (o solo ocasionalmente),NaN,Habitualmente,De vez en cuando,No consumo,No consumo,NaN,NaN,No,NaN,NaN,Nunca,Habitualmente,Habitualmente,Excelente,No,No,No,No,No,NaN,NaN,NaN,NaN,No,No,No,No,No,No,NaN,NaN,No,No,No,No,No,No,NaN,No,No,No,No,No,NaN,NaN,No,No,No,No,NaN,NaN,No,No,No,No,No,NaN,NaN,No,No,Bueno,No,Sí,No,No,Si,No,Si,Si,No,No,No,No,No,Si,No,No,No,Si,No,Si,No,NaN,Si,Si,Si,NaN,NaN,NaN,NaN,No,Si,NaN,No,No,No,no
4758,29790,Benajarafe,Hombre:,61,77.0,171,Piso en bloque de menos 50 viviendas,Bajo (apenas tránsito de personas y/o vehículos),0,NaN,Ámbito administrativo,NaN,En lugares abiertos y cerrados por igual,Media,Nula,Nula,Nula,Muy baja,Nula,Media,Si/Portugal,No he salido de mi comunidad,29790.0,Benajarafe,Piso en bloque de menos 50 viviendas,Medio (movimiento de residentes),2,36 y 32,No,NaN,NaN,NaN,NaN,NaN,NaN,Mediante teletrabajo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,En el hogar (teletrabajo/en paro/ tareas domésticas/confinado),Marzo,NaN,NaN,NaN,Muy frecuentemente,Algunas veces,Muy frecuentemente,Muy frecuentemente,Nunca,No,NaN,NaN,NaN,NaN,De vez en cuando,NaN,NaN,No,No,No,Nunca,Habitualmente,Habitualmente,Excelente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,No,No,No,No,NaN,No,No,No,No,No,NaN,NaN,No,No,No,No,NaN,NaN,No,No,No,No,No,NaN,NaN,No,No,Bueno,No,No,No,No,No,No,NaN,No,No,No,No,No,No,No,No,No,No,No,Si,No,No,NaN,No,No,No,No,No,No,No,No,No,NaN,NaN,No,No,no
4759,29790,Benajarafe,Hombre:,61,77.0,171,Piso en bloque de menos 50 viviendas,Bajo (apenas tránsito de personas y/o vehículos),0,NaN,Ámbito administrativo,NaN,En lugares abiertos y cerrados por igual,Media,Nula,Nula,Nula,Muy baja,Nula,Media,Si/Portugal,No he salido de mi comunidad,29790.0,Benajarafe,Piso en bloque de menos 50 viviendas,Medio (movimiento de residentes),2,36 y 32,No,NaN,NaN,NaN,NaN,NaN,NaN,Mediante teletrabajo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,En el hogar (teletrabajo/en paro/ tareas domésticas/confinado),Marzo,NaN,NaN,NaN,Muy frecuentemente,Algunas veces,Muy frecuentemente,Muy frecuentemente,Nunca,No,NaN,NaN,NaN,NaN,De vez en cuando,NaN,NaN,No,No,No,Nunca,Habitualmente,Habitualmente,Excelente,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,No,No,No,No,NaN,No,No,No,No,No,NaN,NaN,No,No,No,No,NaN,NaN,No,No,No,No,No,NaN,NaN,No,No,Bueno,No,No,No,No,No,No,NaN,No,No,No,No,No,No,No,No,No,No,No,Si,No,No,NaN,No,No,No,No,No,No,No,No,No,NaN,NaN,No,No,no
4788,29012,Victoria,Mujer:,47,70.0,173,Piso en bloque de menos 50 viviendas,Bajo (apenas tránsito de personas y/o vehículos),0,0,Ámbito sanitario o de cuidados a terceros,NaN,NaN,Frecuente,Media,Muy baja,Muy baja,Nula,Nula,Muy baja,Si! Holanda,No he salido de mi comunidad,29012.0,Victoria,Piso en bloque de menos 50 viviendas,Bajo (apenas tránsito de personas y/o vehículos),0,0,Perro,NaN,NaN,NaN,NaN,Mediante teletrabajo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,En el hogar (teletrabajo/en paro/ tareas domésticas/confinado),Marzo,NaN,NaN,NaN,Muy frecuentemente,Frecuentemente,Muy frecuentemente,Frecuentemente,Nunca,NaN,NaN,De vez en cuando,No consumo,Habitualmente,No consumo,NaN,NaN,NaN,NaN,No,Nunca,Nunca,Nunca,Bueno,No,No,No,No,No,No,No,NaN,NaN,No,No,No,No,Si,No,NaN,NaN,No,No,No,NaN,NaN,No,NaN,No,No,No,No,No,NaN,NaN,No,No,No,No,NaN,NaN,No,No,No,No,No,NaN,NaN,No,No,Bueno,No,No,NaN,No,Si,No,Si,Si,Si,Si,NaN,No,No,No,No,No,No,No,No,Si,No,NaN,Si,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,No,no
4791,29012,Victoria,Mujer:,47,70.0,173,Piso en bloque de menos 50 viviendas,Bajo (apenas tránsito de personas y/o vehículos),0,0,Ámbito sanitario o de cuidados a terceros,NaN,NaN,Frecuente,Media,Muy baja,Muy baja,Nula,Nula,Muy baja,Si! Holanda,No he salido de mi comunidad,29012.0,Victoria,Piso en bloque de menos 50 viviendas,Bajo (apenas tránsito de personas y/o vehículos),0,0,Perro,NaN,NaN,NaN,NaN,Mediante teletrabajo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,En el hogar (teletrabajo/en paro/ tareas domésticas/confinado),Marzo,NaN,NaN,NaN,Muy frecuentemente,Frecuentemente,Muy frecuentemente,Frecuentemente,Nunca,NaN,NaN,De vez en cuando,No consumo,Habitualmente,No consumo,NaN,NaN,NaN,NaN,No,Nunca,Nunca,Nunca,Bueno,No,No,No,No,No,No,No,NaN,NaN,No,No,No,No,Si,No,NaN,NaN,No,No,No,NaN,NaN,No,NaN,No,No,No,No,No,NaN,NaN,No,No,No,No,NaN,NaN,No,No,No,No,No,NaN,NaN,No,No,Bueno,No,No,NaN,No,Si,No,Si,Si,Si,Si,NaN,No,No,No,No,No,No,No,No,Si,No,NaN,Si,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,No,no

Hay 4 valores duplicados.

In [15]:
# TODO: ejemplos de búsqueda de valores con espacios o tokens sospechosos
# for c in df_trabajo.columns:
#     ...

cont = 0
tokens = ["Otro", "No se", "NS/NC", "-", "N/A", "Desconocido", "No sé, no me consta", "No se, no me consta", ",", "NA"]

for c in df_trabajo.select_dtypes(["object", "string"]).columns:
    cont += (df_trabajo[c].str.strip() != df_trabajo[c]).sum()

print(f"Hay {cont} valores con espacios iniciales/finales.")
print(f"Los tokens sospechosos los quitamos anteriormente en el apartado 3.")

Hay 5747 valores con espacios iniciales/finales.
Los tokens sospechosos los quitamos anteriormente en el apartado 3.

In [15]:
# TODO: identifica columnas con posible contenido numérico guardado como texto
# pista: intenta convertir con pd.to_numeric(errors="coerce") y compara cuántos valores sobreviven

cols = []
for c in df_trabajo.select_dtypes(["object", "string"]).columns:
    num = pd.to_numeric(df_trabajo[c], errors="coerce")

    if num.notna().any():
        cols.append(c)

print(cols)
print(f"Estas son las columnas que contienen valores numéricos pero no se almacenan como numéricos.")

['1.CPBARRIO-ANTES_1', '1.CPBARRIO-ANTES_2', '3.EDAD_1', '5TALLA_1', '8.CONVIVENCIA-ANTES_1', '9.ED,DES-,NTES_1', '16.CPBARRIO-DURANTE_2', '19.CONVIVENCIA-DURANTE_1', '20.EDADES-DURANTE_1']
Estas son las columnas que contienen valores numéricos pero no se almacenan como numéricos.

# 6. Trabajo obligatorio por bloques del cuestionario

A continuación debes trabajar **bloque a bloque**.  
En cada bloque:

1. Muestra las columnas reales del dataframe que pertenecen a ese bloque.
2. Para **cada columna**:
   - inspecciona valores;
   - detecta problemas;
   - decide una estrategia;
   - escribe el código de limpieza.
3. Actualiza `auditoria`.

**Muy importante:** no basta con decir “esta columna está bien”. Debes demostrarlo con código.

## Bloque P1 — Hábitos de convivencia y sociales **ANTES** del confinamiento

Preguntas que debes revisar en este bloque:

- **1 y 1.1**: código postal y barrio antes del confinamiento.
- **2**: sexo.
- **3, 4, 5**: edad, peso y talla.
- **6 y 7**: tipo de domicilio y afluencia.
- **8 y 9**: número y edades de convivientes.
- **10, 11, 12**: profesión, lugar de trabajo y tiempo libre.
- **13**: transporte habitual.
- **14**: viaje al extranjero.
- **15**: desplazamiento dentro de España.

### Sugerencias específicas

- En códigos postales, cuidado con **ceros a la izquierda**.
- En barrio/ocupación/lugar de trabajo pueden aparecer variantes tipográficas o abreviaturas.
- En edad, peso, talla y convivencia debes buscar **outliers** y valores imposibles.
- En `9` y `13` puede haber respuestas compuestas o listas.
- En `14` puede convenir separar **indicador de viaje** y **destino**.

In [18]:
preguntas_p1 = ["1", "1.1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"]
cols_p1 = columnas_por_bloque(df_trabajo, preguntas_p1)

display(auditoria[auditoria["columna_original"].isin(cols_p1)])

,columna_original,pregunta,dtype_raw,n_missing,pct_missing,n_unicos,bloque,descripcion,tipo_sugerido,foco_limpieza,problemas_detectados,estrategia_aplicada,columnas_generadas
0,1.CPBARRIO-ANTES_1,1,object,1,0.833333,92,P1,Código postal antes del confinamiento,texto/código,"longitud, dígitos, ceros a la izquierda, faltantes",,,
1,1.CPBARRIO-ANTES_2,1,str,12,10.000000,97,P1,Código postal antes del confinamiento,texto/código,"longitud, dígitos, ceros a la izquierda, faltantes",,,
2,2.SEXO_1,2,str,1,0.833333,2,P1,Sexo,categórica nominal,"H/M, Hombre/Mujer, mayúsculas, categorías extrañas",,,
3,3.EDAD_1,3,object,0,0.000000,46,P1,Edad,numérica,"conversión a número, valores imposibles, outliers, imputación",,,
4,4.PESO_1,4,float64,0,0.000000,37,P1,Peso (kg),numérica,"conversión a número, unidades, extremos, ceros/imposibles",,,
5,5TALLA_1,5,object,0,0.000000,7,P1,Talla (cm),numérica,"conversión a número, cm frente a m, extremos, ceros/imposibles",,,
6,6.DOMICILIO-ANTES_1,6,str,0,0.000000,4,P1,Tipo de domicilio antes,categórica nominal,"unificar categorías, otros, faltantes",,,
7,7.AFLUENCIA-ANTES_1,7,str,41,34.166667,2,P1,Afluencia en la zona antes,categórica ordinal,"bajo/medio/alto, orden lógico, variantes de texto",,,
8,8.CONVIVENCIA-ANTES_1,8,object,0,0.000000,1,P1,Número de convivientes antes,numérica discreta,"enteros, negativos, extremos, faltantes",,,
9,"9.ED,DES-,NTES_1",9,object,80,66.666667,3,P1,Edades de convivientes antes,texto/lista,"listas mal formadas, separadores, extracción de resúmenes",,,
10,10.PROFESION-ANTES_1,10,str,8,6.666667,27,P1,Ámbito profesional antes,categórica nominal,"sinónimos, otros, categorías mezcladas",,,
11,11.LUGARTRABAJO-ANTES_1,11,str,92,76.666667,16,P1,Descripción del lugar de trabajo antes,categórica nominal,unificación y categorías raras,,,
12,12.OCIO_1,12,str,46,38.333333,3,P1,Tiempo libre antes,categórica nominal,unificación y categoría 'Otro',,,
13,13.TRANSPORTE_1,13,str,12,10.000000,5,P1,Medio de transporte habitual antes,tabla/orden de preferencias,"listas, separadores, categorías redundantes",,,
14,13.TRANSPORTE_2,13,str,33,27.500000,5,P1,Medio de transporte habitual antes,tabla/orden de preferencias,"listas, separadores, categorías redundantes",,,
15,13.TRANSPORTE_3,13,str,38,31.666667,4,P1,Medio de transporte habitual antes,tabla/orden de preferencias,"listas, separadores, categorías redundantes",,,
16,13.TRANSPORTE_4,13,str,33,27.500000,5,P1,Medio de transporte habitual antes,tabla/orden de preferencias,"listas, separadores, categorías redundantes",,,
17,13.TRANSPORTE_5,13,str,31,25.833333,5,P1,Medio de transporte habitual antes,tabla/orden de preferencias,"listas, separadores, categorías redundantes",,,
18,13.TRANSPORTE_6,13,str,36,30.000000,5,P1,Medio de transporte habitual antes,tabla/orden de preferencias,"listas, separadores, categorías redundantes",,,
19,13.TRANSPORTE_7,13,str,17,14.166667,5,P1,Medio de transporte habitual antes,tabla/orden de preferencias,"listas, separadores, categorías redundantes",,,
20,14.EXTRANJERO_1,14,str,6,5.000000,20,P1,Viaje al extranjero,mixta sí/no + texto,"separar indicador y destino, faltantes",,,
21,15.DESPLAZAMIENTO-NACIONAL_1,15,str,46,38.333333,3,P1,Desplazamiento dentro de España,categórica nominal,sí/no/madrid/barcelona/otra/otro,,,

In [40]:
# TODO P1:
# 1) inspecciona una por una las columnas de cols_p1;
# 2) crea columnas limpias cuando sea necesario;
# 3) actualiza auditoria.
#
# Ejemplos orientativos de inspección:
# for c in cols_p1:
#     resumen_columna(df_trabajo, c)

print(f"Primero vamos a ver en general un resumen de cada columna:")
for c in cols_p1:
    resumen_columna(df_trabajo, c, top=120)

Primero vamos a ver en general un resumen de cada columna:

              columna   dtype    n  n_missing  pct_missing  n_unicos
0  1.CPBARRIO-ANTES_1  object  120          1     0.833333        92

Primeros valores no nulos:

4680    14005
4681    28002
4682    29006
4683    38204
4684    38201
4685    29010
4686    29014
4687    14006
4688    29190
4689    26540
4690    46600
4691    25002
4692    29013
4693    29018
4694    41003
4695    28002
4696    29160
4697    35008
4698    08013
4699    29011
4700    29012
4701    29130
4702    29620
4703    16004
4704    29640
4705    29009
4706    29601
4707    29002
4708    28905
4709    41002
4710    41010
4711    13170
4712    46021
4713     1050
4714    19001
4715    41927
4716    14003
4717    51002
4718    15895
4720    01012
4721    29700
4722    29018
4723    29590
4724    29130
4725    29002
4726    14220
4727    29016
4728    29010
4729    29010
4730    11190
4731    29001
4732    29003
4733    29007
4734    08015
4735    14420
4736    29011
4737    29011
4738    06001
4739    29011
4740    25266
4741    29010
4742    03190
4743    13002
4744    29002
4745    29017
4746    28027
4747    23400
4748    24402
4749    13700
4750    45001
4751    29007
4752    47013
4753    14500
4754    41003
4755    14500
4756    28050
4757    29002
4758    29790
4759    29790
4760    46980
4761    04770
4762    08292
4763    50130
4764    29140
4765    36001
4766    18012
4767    08004
4768    35007
4769    29018
4770    11008
4771    28042
4772    29680
4773    46520
4774    38390
4775    21110
4776    29620
4777     5418
4778    29601
4779    28018
4780    17240
4781    29010
4782    29370
4783    29012
4784    29004
4785    28814
4786    29740
4787    29013
4788    29012
4789    29010
4790    28028
4791    29012
4792    29008
4793    29002
4794    29010
4795    28019
4796    28004
4797    36210
4798    18012
4799    03690
Name: 1.CPBARRIO-ANTES_1, dtype: str

Frecuencias (incluyendo NA):

1.CPBARRIO-ANTES_1
29010    7
29002    5
29011    4
29018    3
28002    2
29013    2
41003    2
29012    2
29130    2
29620    2
29601    2
29007    2
14500    2
29790    2
18012    2
29012    2
14005    1
29006    1
38204    1
38201    1
29014    1
14006    1
29190    1
26540    1
46600    1
25002    1
29160    1
35008    1
08013    1
16004    1
29640    1
29009    1
28905    1
41002    1
41010    1
13170    1
46021    1
1050     1
19001    1
41927    1
14003    1
51002    1
15895    1
NaN      1
01012    1
29700    1
29590    1
14220    1
29016    1
11190    1
29001    1
29003    1
08015    1
14420    1
06001    1
25266    1
03190    1
13002    1
29017    1
28027    1
23400    1
24402    1
13700    1
45001    1
47013    1
28050    1
46980    1
04770    1
08292    1
50130    1
29140    1
36001    1
08004    1
35007    1
11008    1
28042    1
29680    1
46520    1
38390    1
21110    1
5418     1
28018    1
17240    1
29370    1
29004    1
28814    1
29740    1
28028    1
29008    1
28019    1
28004    1
36210    1
03690    1
Name: count, dtype: int64

              columna dtype    n  n_missing  pct_missing  n_unicos
0  1.CPBARRIO-ANTES_2   str  120         12         10.0        97

Primeros valores no nulos:

4680                          14005
4681                    Prosperidad
4682     Cruz Humilladero ( Málaga)
4683                Casco histórico
4684               La Laguna Centro
4685                          29010
4686                 Ciudad Jardín
4687             Huerta de la reina
4688             Puerto de la torre
4689                         Alfaro
4690                         Alzira
4692                    Almendrsles
4693                        El Palo
4694                 Sevilla Centro
4696                    Casabermeja
4697    Las palmas de gran Canaria
4698                       Eixample
4699                       Virreina
4700                       Victoria
4701           Alhaurín de la torre
4702                      Playamar
4703         Los tiradores (cuenca)
4704                       Montemar
4705                          29009
4706                Ricardo Soriano
4708                          28905
4709            Alameda de Hercules
4710                         Triana
4711                    Miguelturra
4712                       San Jose
4713                       Bruselas
4714                    Guadalajara
4715                       Cavaleri
4717                   Villajovita
4718                     Milladoiro
4720                       El pilar
4721                   Velez Malaga
4722                        El palo
4723                   Campanillas
4724           Alhaurín de la Torre
4725                        centro
4727                        Limonar
4728         La colonia Santa Inés
4729                       Teatinos
4730           Benalup Casas Viejas
4731                         Malaga
4732                         Torcal
4733                    Haza Cuevas
4735                       El mismo
4736                       Virreina
4737                       Virreina
4738                 centro  ciudad
4739                     Miraflores
4740                          Rural
4741                      el cónsul
4742                   Los Segundas
4743               Ronda del carmen
4744                        Perchel
4745                    Pedregalejo
4746                       Salvador
4747                          Ubeda
4748        Polígono de las Huertas
4749                         Centro
4750               Casco histórico
4751               Centro histórico
4752                       Delicias
4753                   Puente Genil
4754                    Santa Justa
4755                   Puente Genil
4756                    Las tablas
4757                        Hueling
4758                     Benajarafe
4759                     Benajarafe
4760                    campamento
4761                           Adra
4762                           Font
4763                    extrarradio
4764                      Churriana
4765                  Benito Corbal
4766                         Centro
4768                    Guanarteme
4769                        El Palo
4770                       Asdrúbal
4771               Alameda de Osuna
4772                     San Roque
4774                    El Calvario
4775                      Aljaraque
4776         Playamar/Torremolinos
4777                           5418
4778                Marbella centro
4779                       Vallecas
4780                     Llagostera
4781                       Teatinos
4783                         Malaga
4784                      Guadalmar
4786                      Zona Faro
4787                      Victoria
4788                      Victoria
4789               Centro histórico
4791                      Victoria
4792                        Centro
4793                         Huelin
4794                 Ciudad jardin
4795           Carabanchel (Madrid)
4796                       Malasaña
4797                      Castrelos
4798                     San Lázaro
4799                     zona norte
Name: 1.CPBARRIO-ANTES_2, dtype: str

Frecuencias (incluyendo NA):

1.CPBARRIO-ANTES_2
NaN                            12
Virreina                        3
Victoria                        3
El Palo                         2
Teatinos                        2
Malaga                          2
Centro                          2
Centro histórico                2
Puente Genil                    2
Benajarafe                      2
14005                           1
Prosperidad                     1
Cruz Humilladero ( Málaga)      1
Casco histórico                 1
La Laguna Centro                1
29010                           1
Ciudad Jardín                   1
Huerta de la reina              1
Puerto de la torre              1
Alfaro                          1
Alzira                          1
Almendrsles                     1
Sevilla Centro                  1
Casabermeja                     1
Las palmas de gran Canaria      1
Eixample                        1
Victoria                        1
Alhaurín de la torre            1
Playamar                        1
Los tiradores (cuenca)          1
Montemar                        1
29009                           1
Ricardo Soriano                 1
28905                           1
Alameda de Hercules             1
Triana                          1
Miguelturra                     1
San Jose                        1
Bruselas                        1
Guadalajara                     1
Cavaleri                        1
Villajovita                     1
Milladoiro                      1
El pilar                        1
Velez Malaga                    1
El palo                         1
Campanillas                     1
Alhaurín de la Torre            1
centro                          1
Limonar                         1
La colonia Santa Inés           1
Benalup Casas Viejas            1
Torcal                          1
Haza Cuevas                     1
El mismo                        1
centro  ciudad                  1
Miraflores                      1
Rural                           1
el cónsul                       1
Los Segundas                    1
Ronda del carmen                1
Perchel                         1
Pedregalejo                     1
Salvador                        1
Ubeda                           1
Polígono de las Huertas         1
Casco histórico                 1
Delicias                        1
Santa Justa                     1
Las tablas                      1
Hueling                         1
campamento                      1
Adra                            1
Font                            1
extrarradio                     1
Churriana                       1
Benito Corbal                   1
Guanarteme                      1
Asdrúbal                        1
Alameda de Osuna                1
San Roque                       1
El Calvario                     1
Aljaraque                       1
Playamar/Torremolinos           1
5418                            1
Marbella centro                 1
Vallecas                        1
Llagostera                      1
Guadalmar                       1
Zona Faro                       1
Centro                          1
Huelin                          1
Ciudad jardin                   1
Carabanchel (Madrid)            1
Malasaña                        1
Castrelos                       1
San Lázaro                      1
zona norte                      1
Name: count, dtype: int64

    columna dtype    n  n_missing  pct_missing  n_unicos
0  2.SEXO_1   str  120          1     0.833333         2

Primeros valores no nulos:

4680    Hombre:
4681     Mujer:
4682     Mujer:
4683     Mujer:
4684     Mujer:
4685     Mujer:
4686     Mujer:
4687     Mujer:
4688    Hombre:
4689    Hombre:
4690     Mujer:
4691    Hombre:
4692     Mujer:
4693     Mujer:
4694     Mujer:
4695     Mujer:
4696     Mujer:
4697     Mujer:
4698     Mujer:
4699     Mujer:
4700     Mujer:
4701    Hombre:
4702     Mujer:
4703     Mujer:
4704    Hombre:
4705     Mujer:
4706     Mujer:
4707     Mujer:
4708     Mujer:
4709     Mujer:
4710     Mujer:
4711    Hombre:
4712    Hombre:
4713     Mujer:
4714    Hombre:
4715    Hombre:
4716     Mujer:
4717     Mujer:
4718    Hombre:
4719    Hombre:
4720     Mujer:
4721    Hombre:
4722     Mujer:
4723     Mujer:
4724     Mujer:
4725    Hombre:
4726    Hombre:
4727    Hombre:
4728     Mujer:
4729     Mujer:
4730     Mujer:
4731     Mujer:
4732     Mujer:
4733    Hombre:
4734     Mujer:
4735    Hombre:
4736     Mujer:
4737     Mujer:
4738    Hombre:
4739     Mujer:
4740     Mujer:
4741    Hombre:
4742    Hombre:
4743     Mujer:
4744    Hombre:
4745     Mujer:
4746     Mujer:
4747    Hombre:
4748     Mujer:
4749    Hombre:
4750     Mujer:
4751     Mujer:
4752    Hombre:
4753     Mujer:
4754    Hombre:
4755     Mujer:
4756     Mujer:
4757    Hombre:
4758    Hombre:
4759    Hombre:
4760     Mujer:
4761     Mujer:
4762    Hombre:
4763    Hombre:
4764    Hombre:
4765    Hombre:
4766    Hombre:
4767     Mujer:
4768    Hombre:
4769     Mujer:
4770     Mujer:
4771    Hombre:
4772     Mujer:
4773    Hombre:
4775    Hombre:
4776    Hombre:
4777     Mujer:
4778     Mujer:
4779    Hombre:
4780    Hombre:
4781     Mujer:
4782    Hombre:
4783     Mujer:
4784    Hombre:
4785    Hombre:
4786     Mujer:
4787    Hombre:
4788     Mujer:
4789     Mujer:
4790     Mujer:
4791     Mujer:
4792     Mujer:
4793    Hombre:
4794     Mujer:
4795    Hombre:
4796    Hombre:
4797    Hombre:
4798     Mujer:
4799    Hombre:
Name: 2.SEXO_1, dtype: str

Frecuencias (incluyendo NA):

2.SEXO_1
Mujer:     69
Hombre:    50
NaN         1
Name: count, dtype: int64

    columna   dtype    n  n_missing  pct_missing  n_unicos
0  3.EDAD_1  object  120          0          0.0        46

Primeros valores no nulos:

4680    42
4681    56
4682    33
4683    65
4684    63
4685    25
4686    38
4687    30
4688    46
4689    42
4690    40
4691    50
4692    61
4693    55
4694    26
4695    41
4696    29
4697    29
4698    74
4699    46
4700    52
4701    60
4702    38
4703    26
4704    66
4705    34
4706    67
4707    26
4708    41
4709    40
4710    31
4711    29
4712    71
4713    38
4714    26
4715    75
4716    31
4717    63
4718    33
4719    73
4720    33
4721    56
4722    47
4723    38
4724    34
4725    42
4726    55
4727    76
4728    34
4729    56
4730    26
4731    37
4732    42
4733    55
4734    44
4735    62
4736    37
4737    37
4738    58
4739    26
4740    67
4741    47
4742    50
4743    59
4744    66
4745    32
4746    64
4747    52
4748    37
4749    62
4750    34
4751    38
4752    53
4753    33
4754    59
4755    33
4756    45
4757    53
4758    61
4759    61
4760    36
4761    39
4762    45
4763    47
4764    41
4765    36
4766    28
4767    42
4768    58
4769    33
4770    56
4771    81
4772    30
4773    40
4774    42
4775    36
4776    54
4777    43
4778    57
4779    39
4780    46
4781    56
4782    62
4783    38
4784    57
4785    59
4786    54
4787    56
4788    47
4789    47
4790    28
4791    47
4792    49
4793    54
4794    29
4795    30
4796    32
4797    44
4798    53
4799    48
Name: 3.EDAD_1, dtype: str

Frecuencias (incluyendo NA):

3.EDAD_1
42    6
56    6
33    6
38    6
26    6
47    6
29    4
34    4
37    4
30    3
46    3
40    3
61    3
55    3
41    3
62    3
59    3
53    3
36    3
54    3
63    2
50    2
52    2
66    2
67    2
31    2
44    2
58    2
32    2
45    2
39    2
28    2
57    2
65    1
25    1
74    1
60    1
71    1
75    1
73    1
76    1
64    1
81    1
43    1
49    1
48    1
Name: count, dtype: int64

    columna    dtype    n  n_missing  pct_missing  n_unicos
0  4.PESO_1  float64  120          0          0.0        37

Primeros valores no nulos:

4680     72.0
4681     65.0
4682     88.0
4683     58.0
4684     59.0
4685     63.0
4686     73.0
4687     58.0
4688     74.0
4689     86.0
4690     88.0
4691     65.0
4692     62.0
4693     78.0
4694     56.0
4695     57.5
4696     60.0
4697     65.0
4698     90.0
4699     72.0
4700     62.0
4701     74.0
4702     66.0
4703     53.0
4704     84.0
4705     60.0
4706     68.0
4707     61.0
4708     63.0
4709     58.0
4710     60.0
4711     61.0
4712     87.0
4713     60.0
4714     64.0
4715     70.0
4716     58.0
4717     62.0
4718     70.0
4719     75.0
4720     65.0
4721     90.0
4722     73.0
4723     60.0
4724     56.0
4725     67.0
4726     86.0
4727     73.0
4728     66.0
4729     65.0
4730     62.0
4731     58.0
4732     80.0
4733     70.0
4734     65.0
4735     80.0
4736     54.0
4737     54.0
4738     73.0
4739     70.0
4740     68.0
4741     90.0
4742     73.0
4743    100.0
4744     80.0
4745     65.0
4746     62.0
4747     78.0
4748     75.0
4749     65.0
4750     64.0
4751     90.0
4752     65.0
4753     59.0
4754     60.0
4755     59.0
4756     63.0
4757     70.0
4758     77.0
4759     77.0
4760     63.0
4761     64.0
4762     75.0
4763     81.0
4764     86.0
4765     60.0
4766     69.0
4767     55.0
4768    104.0
4769     64.0
4770     86.0
4771     74.0
4772     60.0
4773     82.0
4774     90.0
4775     82.6
4776     84.0
4777     67.0
4778     79.0
4779     90.0
4780     77.0
4781     64.0
4782     68.0
4783     68.0
4784     73.0
4785     72.0
4786     57.0
4787     68.0
4788     70.0
4789     90.0
4790     61.0
4791     70.0
4792     56.0
4793     81.0
4794     70.0
4795     90.0
4796     70.0
4797     82.0
4798     58.0
4799     62.0
Name: 4.PESO_1, dtype: str

Frecuencias (incluyendo NA):

4.PESO_1
65.0     9
70.0     9
60.0     8
90.0     8
58.0     6
73.0     6
62.0     6
68.0     5
64.0     5
63.0     4
86.0     4
72.0     3
59.0     3
74.0     3
56.0     3
61.0     3
75.0     3
80.0     3
77.0     3
88.0     2
78.0     2
66.0     2
84.0     2
67.0     2
54.0     2
81.0     2
82.0     2
57.5     1
53.0     1
87.0     1
100.0    1
69.0     1
55.0     1
104.0    1
82.6     1
79.0     1
57.0     1
Name: count, dtype: int64

    columna   dtype    n  n_missing  pct_missing  n_unicos
0  5TALLA_1  object  120          0          0.0         7

Primeros valores no nulos:

4680    167
4681    167
4682    167
4683    167
4684    167
4685    167
4686    167
4687    167
4688    167
4689    167
4690    167
4691    167
4692    168
4693    168
4694    168
4695    168
4696    168
4697    168
4698    168
4699    168
4700    168
4701    169
4702    169
4703    169
4704    169
4705    169
4706    169
4707    169
4708    169
4709    169
4710    169
4711    169
4712    169
4713    169
4714    169
4715    169
4716    169
4717    170
4718    170
4719    170
4720    170
4721    170
4722    170
4723    170
4724    170
4725    170
4726    170
4727    170
4728    170
4729    170
4730    170
4731    170
4732    170
4733    170
4734    170
4735    170
4736    170
4737    170
4738    170
4739    170
4740    170
4741    170
4742    170
4743    170
4744    170
4745    170
4746    170
4747    170
4748    170
4749    170
4750    170
4751    170
4752    170
4753    170
4754    170
4755    170
4756    170
4757    170
4758    171
4759    171
4760    171
4761    171
4762    171
4763    171
4764    172
4765    172
4766    172
4767    172
4768    172
4769    172
4770    172
4771    172
4772    172
4773    172
4774    172
4775    172
4776    172
4777    172
4778    172
4779    173
4780    173
4781    173
4782    173
4783    173
4784    173
4785    173
4786    173
4787    173
4788    173
4789    173
4790    173
4791    173
4792    173
4793    173
4794    173
4795    173
4796    173
4797    173
4798    173
4799    173
Name: 5TALLA_1, dtype: str

Frecuencias (incluyendo NA):

5TALLA_1
170    41
173    21
169    16
172    15
167    12
168     9
171     6
Name: count, dtype: int64

               columna dtype    n  n_missing  pct_missing  n_unicos
0  6.DOMICILIO-ANTES_1   str  120          0          0.0         4

Primeros valores no nulos:

4680     Piso en bloque de menos 50 viviendas
4681     Piso en bloque de menos 50 viviendas
4682     Piso en bloque de menos 50 viviendas
4683     Piso en bloque de menos 50 viviendas
4684     Piso en bloque de menos 50 viviendas
4685     Piso en bloque de menos 50 viviendas
4686     Piso en bloque de menos 50 viviendas
4687     Piso en bloque de menos 50 viviendas
4688     Piso en bloque de menos 50 viviendas
4689     Piso en bloque de menos 50 viviendas
4690                         Casa unifamiliar
4691     Piso en bloque de menos 50 viviendas
4692     Piso en bloque de menos 50 viviendas
4693     Piso en bloque de menos 50 viviendas
4694     Piso en bloque de menos 50 viviendas
4695     Piso en bloque de menos 50 viviendas
4696                         Casa unifamiliar
4697     Piso en bloque de menos 50 viviendas
4698    Piso en bloque de más de 50 viviendas
4699     Piso en bloque de menos 50 viviendas
4700     Piso en bloque de menos 50 viviendas
4701                         Casa unifamiliar
4702    Piso en bloque de más de 50 viviendas
4703     Piso en bloque de menos 50 viviendas
4704     Piso en bloque de menos 50 viviendas
4705     Piso en bloque de menos 50 viviendas
4706     Piso en bloque de menos 50 viviendas
4707     Piso en bloque de menos 50 viviendas
4708    Piso en bloque de más de 50 viviendas
4709     Piso en bloque de menos 50 viviendas
4710     Piso en bloque de menos 50 viviendas
4711                         Casa unifamiliar
4712     Piso en bloque de menos 50 viviendas
4713     Piso en bloque de menos 50 viviendas
4714     Piso en bloque de menos 50 viviendas
4715           Casa con espacio al aire libre
4716     Piso en bloque de menos 50 viviendas
4717     Piso en bloque de menos 50 viviendas
4718     Piso en bloque de menos 50 viviendas
4719                         Casa unifamiliar
4720     Piso en bloque de menos 50 viviendas
4721                         Casa unifamiliar
4722     Piso en bloque de menos 50 viviendas
4723     Piso en bloque de menos 50 viviendas
4724     Piso en bloque de menos 50 viviendas
4725     Piso en bloque de menos 50 viviendas
4726                         Casa unifamiliar
4727     Piso en bloque de menos 50 viviendas
4728    Piso en bloque de más de 50 viviendas
4729    Piso en bloque de más de 50 viviendas
4730     Piso en bloque de menos 50 viviendas
4731     Piso en bloque de menos 50 viviendas
4732    Piso en bloque de más de 50 viviendas
4733     Piso en bloque de menos 50 viviendas
4734     Piso en bloque de menos 50 viviendas
4735                         Casa unifamiliar
4736     Piso en bloque de menos 50 viviendas
4737     Piso en bloque de menos 50 viviendas
4738     Piso en bloque de menos 50 viviendas
4739     Piso en bloque de menos 50 viviendas
4740                         Casa unifamiliar
4741    Piso en bloque de más de 50 viviendas
4742     Piso en bloque de menos 50 viviendas
4743     Piso en bloque de menos 50 viviendas
4744    Piso en bloque de más de 50 viviendas
4745                         Casa unifamiliar
4746     Piso en bloque de menos 50 viviendas
4747     Piso en bloque de menos 50 viviendas
4748    Piso en bloque de más de 50 viviendas
4749     Piso en bloque de menos 50 viviendas
4750     Piso en bloque de menos 50 viviendas
4751     Piso en bloque de menos 50 viviendas
4752     Piso en bloque de menos 50 viviendas
4753     Piso en bloque de menos 50 viviendas
4754     Piso en bloque de menos 50 viviendas
4755     Piso en bloque de menos 50 viviendas
4756                         Casa unifamiliar
4757    Piso en bloque de más de 50 viviendas
4758     Piso en bloque de menos 50 viviendas
4759     Piso en bloque de menos 50 viviendas
4760     Piso en bloque de menos 50 viviendas
4761     Piso en bloque de menos 50 viviendas
4762                         Casa unifamiliar
4763           Casa con espacio al aire libre
4764    Piso en bloque de más de 50 viviendas
4765                         Casa unifamiliar
4766     Piso en bloque de menos 50 viviendas
4767     Piso en bloque de menos 50 viviendas
4768    Piso en bloque de más de 50 viviendas
4769     Piso en bloque de menos 50 viviendas
4770     Piso en bloque de menos 50 viviendas
4771     Piso en bloque de menos 50 viviendas
4772     Piso en bloque de menos 50 viviendas
4773     Piso en bloque de menos 50 viviendas
4774     Piso en bloque de menos 50 viviendas
4775                         Casa unifamiliar
4776                         Casa unifamiliar
4777     Piso en bloque de menos 50 viviendas
4778                         Casa unifamiliar
4779     Piso en bloque de menos 50 viviendas
4780                         Casa unifamiliar
4781    Piso en bloque de más de 50 viviendas
4782                         Casa unifamiliar
4783     Piso en bloque de menos 50 viviendas
4784    Piso en bloque de más de 50 viviendas
4785                         Casa unifamiliar
4786    Piso en bloque de más de 50 viviendas
4787    Piso en bloque de más de 50 viviendas
4788     Piso en bloque de menos 50 viviendas
4789    Piso en bloque de más de 50 viviendas
4790    Piso en bloque de más de 50 viviendas
4791     Piso en bloque de menos 50 viviendas
4792     Piso en bloque de menos 50 viviendas
4793     Piso en bloque de menos 50 viviendas
4794     Piso en bloque de menos 50 viviendas
4795    Piso en bloque de más de 50 viviendas
4796     Piso en bloque de menos 50 viviendas
4797     Piso en bloque de menos 50 viviendas
4798     Piso en bloque de menos 50 viviendas
4799     Piso en bloque de menos 50 viviendas
Name: 6.DOMICILIO-ANTES_1, dtype: str

Frecuencias (incluyendo NA):

6.DOMICILIO-ANTES_1
Piso en bloque de menos 50 viviendas     80
Casa unifamiliar                         19
Piso en bloque de más de 50 viviendas    19
Casa con espacio al aire libre            2
Name: count, dtype: int64

               columna dtype    n  n_missing  pct_missing  n_unicos
0  7.AFLUENCIA-ANTES_1   str  120         41    34.166667         2

Primeros valores no nulos:

4681                    Medio (movimiento de residentes)
4686                    Medio (movimiento de residentes)
4688                    Medio (movimiento de residentes)
4689    Bajo (apenas tránsito de personas y/o vehículos)
4690                    Medio (movimiento de residentes)
4691                    Medio (movimiento de residentes)
4692    Bajo (apenas tránsito de personas y/o vehículos)
4693                    Medio (movimiento de residentes)
4694                    Medio (movimiento de residentes)
4695                    Medio (movimiento de residentes)
4696                    Medio (movimiento de residentes)
4697                    Medio (movimiento de residentes)
4698                    Medio (movimiento de residentes)
4699                    Medio (movimiento de residentes)
4700                    Medio (movimiento de residentes)
4701                    Medio (movimiento de residentes)
4702                    Medio (movimiento de residentes)
4703                    Medio (movimiento de residentes)
4704                    Medio (movimiento de residentes)
4706                    Medio (movimiento de residentes)
4708                    Medio (movimiento de residentes)
4711                    Medio (movimiento de residentes)
4712                    Medio (movimiento de residentes)
4714    Bajo (apenas tránsito de personas y/o vehículos)
4715                    Medio (movimiento de residentes)
4716                    Medio (movimiento de residentes)
4717                    Medio (movimiento de residentes)
4718                    Medio (movimiento de residentes)
4721                    Medio (movimiento de residentes)
4722                    Medio (movimiento de residentes)
4723                    Medio (movimiento de residentes)
4725                    Medio (movimiento de residentes)
4726                    Medio (movimiento de residentes)
4727                    Medio (movimiento de residentes)
4728                    Medio (movimiento de residentes)
4729                    Medio (movimiento de residentes)
4730    Bajo (apenas tránsito de personas y/o vehículos)
4733                    Medio (movimiento de residentes)
4735    Bajo (apenas tránsito de personas y/o vehículos)
4736                    Medio (movimiento de residentes)
4737                    Medio (movimiento de residentes)
4739                    Medio (movimiento de residentes)
4740    Bajo (apenas tránsito de personas y/o vehículos)
4741                    Medio (movimiento de residentes)
4742    Bajo (apenas tránsito de personas y/o vehículos)
4743                    Medio (movimiento de residentes)
4748                    Medio (movimiento de residentes)
4749                    Medio (movimiento de residentes)
4752                    Medio (movimiento de residentes)
4753                    Medio (movimiento de residentes)
4755                    Medio (movimiento de residentes)
4756                    Medio (movimiento de residentes)
4757                    Medio (movimiento de residentes)
4758    Bajo (apenas tránsito de personas y/o vehículos)
4759    Bajo (apenas tránsito de personas y/o vehículos)
4760                    Medio (movimiento de residentes)
4761                    Medio (movimiento de residentes)
4762                    Medio (movimiento de residentes)
4763    Bajo (apenas tránsito de personas y/o vehículos)
4764                    Medio (movimiento de residentes)
4770                    Medio (movimiento de residentes)
4771                    Medio (movimiento de residentes)
4772                    Medio (movimiento de residentes)
4775                    Medio (movimiento de residentes)
4776    Bajo (apenas tránsito de personas y/o vehículos)
4777                    Medio (movimiento de residentes)
4780    Bajo (apenas tránsito de personas y/o vehículos)
4781                    Medio (movimiento de residentes)
4782                    Medio (movimiento de residentes)
4784                    Medio (movimiento de residentes)
4785                    Medio (movimiento de residentes)
4788    Bajo (apenas tránsito de personas y/o vehículos)
4790                    Medio (movimiento de residentes)
4791    Bajo (apenas tránsito de personas y/o vehículos)
4794                    Medio (movimiento de residentes)
4795                    Medio (movimiento de residentes)
4797                    Medio (movimiento de residentes)
4798    Bajo (apenas tránsito de personas y/o vehículos)
4799    Bajo (apenas tránsito de personas y/o vehículos)
Name: 7.AFLUENCIA-ANTES_1, dtype: str

Frecuencias (incluyendo NA):

7.AFLUENCIA-ANTES_1
Medio (movimiento de residentes)                    63
NaN                                                 41
Bajo (apenas tránsito de personas y/o vehículos)    16
Name: count, dtype: int64

                 columna   dtype    n  n_missing  pct_missing  n_unicos
0  8.CONVIVENCIA-ANTES_1  object  120          0          0.0         1

Primeros valores no nulos:

4680    0
4681    0
4682    0
4683    0
4684    0
4685    0
4686    0
4687    0
4688    0
4689    0
4690    0
4691    0
4692    0
4693    0
4694    0
4695    0
4696    0
4697    0
4698    0
4699    0
4700    0
4701    0
4702    0
4703    0
4704    0
4705    0
4706    0
4707    0
4708    0
4709    0
4710    0
4711    0
4712    0
4713    0
4714    0
4715    0
4716    0
4717    0
4718    0
4719    0
4720    0
4721    0
4722    0
4723    0
4724    0
4725    0
4726    0
4727    0
4728    0
4729    0
4730    0
4731    0
4732    0
4733    0
4734    0
4735    0
4736    0
4737    0
4738    0
4739    0
4740    0
4741    0
4742    0
4743    0
4744    0
4745    0
4746    0
4747    0
4748    0
4749    0
4750    0
4751    0
4752    0
4753    0
4754    0
4755    0
4756    0
4757    0
4758    0
4759    0
4760    0
4761    0
4762    0
4763    0
4764    0
4765    0
4766    0
4767    0
4768    0
4769    0
4770    0
4771    0
4772    0
4773    0
4774    0
4775    0
4776    0
4777    0
4778    0
4779    0
4780    0
4781    0
4782    0
4783    0
4784    0
4785    0
4786    0
4787    0
4788    0
4789    0
4790    0
4791    0
4792    0
4793    0
4794    0
4795    0
4796    0
4797    0
4798    0
4799    0
Name: 8.CONVIVENCIA-ANTES_1, dtype: str

Frecuencias (incluyendo NA):

8.CONVIVENCIA-ANTES_1
0    120
Name: count, dtype: int64

            columna   dtype    n  n_missing  pct_missing  n_unicos
0  9.ED,DES-,NTES_1  object  120         80    66.666667         3

Primeros valores no nulos:

4680      0
4683      0
4684      0
4688      0
4689      0
4691      0
4695      0
4698      0
4699      0
4702      0
4706      0
4708      0
4710      0
4711      0
4713      0
4715      0
4716      0
4718      0
4719      0
4730     No
4733      0
4734      0
4742      0
4743      0
4745      0
4748      0
4750      0
4756      0
4761      0
4762      0
4764      0
4772      0
4777      0
4784      0
4788      0
4791      0
4792      0
4795    0.1
4796      0
4799      0
Name: 9.ED,DES-,NTES_1, dtype: str

Frecuencias (incluyendo NA):

9.ED,DES-,NTES_1
NaN    80
0      38
No      1
0.1     1
Name: count, dtype: int64

                columna dtype    n  n_missing  pct_missing  n_unicos
0  10.PROFESION-ANTES_1   str  120          8     6.666667        27

Primeros valores no nulos:

4680                              Ámbito educativo
4681                        Medios de comunicación
4682             Ámbito del ocio y la restauración
4683                              Ámbito educativo
4684                         Ámbito administrativo
4685                                    Estudiante
4686     Ámbito sanitario o de cuidados a terceros
4687                              Ámbito educativo
4688                 Tecnologías de la información
4689                              Ámbito educativo
4690                              Ámbito educativo
4691                              Ámbito educativo
4692                              Ámbito educativo
4693                              Ámbito educativo
4694                              Ámbito educativo
4695                         Ámbito administrativo
4696    Ámbito de la Investigación y el Desarrollo
4697                                     Logopeda
4698                          Sin ocupación previa
4699     Ámbito de la construcción y mantenimiento
4700                              Ámbito educativo
4701     Ámbito sanitario o de cuidados a terceros
4703                              Ámbito educativo
4704                          Sin ocupación previa
4706                          Sin ocupación previa
4707                            Telecomunicaciones
4708                         Ámbito administrativo
4709    Ámbito de la Investigación y el Desarrollo
4710     Ámbito sanitario o de cuidados a terceros
4711                          Sin ocupación previa
4712                                      Jubilado
4713    Ámbito de la Investigación y el Desarrollo
4714                              Ámbito educativo
4716    Ámbito de la Investigación y el Desarrollo
4717                              Ámbito educativo
4718                                desarrollo web
4719     Ámbito sanitario o de cuidados a terceros
4720                              Ámbito comercial
4721     Ámbito sanitario o de cuidados a terceros
4722                             Peluquería canina
4723                         Ámbito administrativo
4724     Ámbito sanitario o de cuidados a terceros
4725    Ámbito de la Investigación y el Desarrollo
4726                             Empleado público
4727                                      Jubilado
4728     Ámbito sanitario o de cuidados a terceros
4729     Ámbito sanitario o de cuidados a terceros
4730                              Ámbito educativo
4731                          Sin ocupación previa
4732     Ámbito de la construcción y mantenimiento
4733                         Ámbito administrativo
4734                         Ámbito administrativo
4735                                  Baja laboral
4736                                    Marketing
4737                                    Marketing
4738                                      jubilado
4739     Ámbito sanitario o de cuidados a terceros
4741                              Ámbito educativo
4742                              Ámbito educativo
4743                              Ámbito comercial
4744                                      Jubilado
4745             Ámbito del ocio y la restauración
4746                          Sin ocupación previa
4747                         Ámbito administrativo
4748                          Sin ocupación previa
4749                                     Jubilado
4750                              Ámbito educativo
4751                         Ámbito administrativo
4752                         Ámbito administrativo
4753                     Investigación y sanitario
4754    Ámbito de la Investigación y el Desarrollo
4755                     Investigación y sanitario
4756    Ámbito de la Investigación y el Desarrollo
4757                              Ámbito educativo
4758                         Ámbito administrativo
4759                         Ámbito administrativo
4761                           Entidad financiera
4762     Ámbito de la construcción y mantenimiento
4764                              Ámbito comercial
4765                              Ámbito educativo
4767                              Ámbito educativo
4768                                     Retirado
4769                              Ámbito educativo
4770                         Ámbito administrativo
4771                                      Jubilado
4772                              Ámbito educativo
4773                              Ámbito educativo
4774    Ámbito de la Investigación y el Desarrollo
4775     Ámbito de la construcción y mantenimiento
4776     Ámbito sanitario o de cuidados a terceros
4777                              Ámbito educativo
4778                         Ámbito administrativo
4780                         Ámbito administrativo
4781                              Ámbito educativo
4782                          Sin ocupación previa
4783                                 Investigación
4784                              Ámbito educativo
4785                          Sin ocupación previa
4786                         Ámbito Salud Pública
4787                              Ámbito educativo
4788     Ámbito sanitario o de cuidados a terceros
4789                         Ámbito administrativo
4790                              Ámbito comercial
4791     Ámbito sanitario o de cuidados a terceros
4792     Ámbito de la construcción y mantenimiento
4793                         Ámbito administrativo
4794                    Industria agroalimentaria
4795    Ámbito de la Investigación y el Desarrollo
4796    Ámbito de la Investigación y el Desarrollo
4797    Ámbito de la Investigación y el Desarrollo
4798                         Ámbito administrativo
4799                              Ámbito educativo
Name: 10.PROFESION-ANTES_1, dtype: str

Frecuencias (incluyendo NA):

10.PROFESION-ANTES_1
Ámbito educativo                              28
Ámbito administrativo                         17
Ámbito sanitario o de cuidados a terceros     12
Ámbito de la Investigación y el Desarrollo    11
Sin ocupación previa                           9
NaN                                            8
Ámbito de la construcción y mantenimiento      5
Jubilado                                       4
Ámbito comercial                               4
Ámbito del ocio y la restauración              2
Marketing                                      2
Investigación y sanitario                      2
Medios de comunicación                         1
Estudiante                                     1
Tecnologías de la información                  1
Logopeda                                       1
Telecomunicaciones                             1
desarrollo web                                 1
Peluquería canina                              1
Empleado público                               1
Baja laboral                                   1
jubilado                                       1
Jubilado                                       1
Entidad financiera                             1
Retirado                                       1
Investigación                                  1
Ámbito Salud Pública                           1
Industria agroalimentaria                      1
Name: count, dtype: int64

                   columna dtype    n  n_missing  pct_missing  n_unicos
0  11.LUGARTRABAJO-ANTES_1   str  120         92    76.666667        16

Primeros valores no nulos:

4680                                                Instituto de Enseñanza Secundaria
4683                                                              Jubilada desde 2018
4686                       Centro de 8 menores + coincidir diariamente5 profesionales
4697    La afluencia en muchas ocasiones era de mas de 10 pero es una pequeña empresa
4698                             En el hogar (teletrabajo/en paro/ tareas domésticas)
4704                                                                        Jubilado
4706                             En el hogar (teletrabajo/en paro/ tareas domésticas)
4710                                                                         Farmacia
4711                             En el hogar (teletrabajo/en paro/ tareas domésticas)
4712                                                                         Jubilado
4715                                                                         jubilado
4719                                                                         Hospital
4726                                  Servicio esencial ( lucha incendios forestales)
4732                                                 Oficina y obras de construcción
4735                             En el hogar (teletrabajo/en paro/ tareas domésticas)
4744                             En el hogar (teletrabajo/en paro/ tareas domésticas)
4746                             En el hogar (teletrabajo/en paro/ tareas domésticas)
4748                             En el hogar (teletrabajo/en paro/ tareas domésticas)
4749                                                                      Depuradora
4763                             En el hogar (teletrabajo/en paro/ tareas domésticas)
4765                                                               Educación infantil
4768                                                                        Retirado
4771                             En el hogar (teletrabajo/en paro/ tareas domésticas)
4777                             En el hogar (teletrabajo/en paro/ tareas domésticas)
4778                                                             OficinaCon afluencia
4782                             En el hogar (teletrabajo/en paro/ tareas domésticas)
4785                             En el hogar (teletrabajo/en paro/ tareas domésticas)
4792                             En el hogar (teletrabajo/en paro/ tareas domésticas)
Name: 11.LUGARTRABAJO-ANTES_1, dtype: str

Frecuencias (incluyendo NA):

11.LUGARTRABAJO-ANTES_1
NaN                                                                              92
En el hogar (teletrabajo/en paro/ tareas domésticas)                             13
Instituto de Enseñanza Secundaria                                                 1
Jubilada desde 2018                                                               1
Centro de 8 menores + coincidir diariamente5 profesionales                        1
La afluencia en muchas ocasiones era de mas de 10 pero es una pequeña empresa     1
Jubilado                                                                          1
Farmacia                                                                          1
Jubilado                                                                          1
jubilado                                                                          1
Hospital                                                                          1
Servicio esencial ( lucha incendios forestales)                                   1
Oficina y obras de construcción                                                   1
Depuradora                                                                        1
Educación infantil                                                                1
Retirado                                                                          1
OficinaCon afluencia                                                              1
Name: count, dtype: int64

     columna dtype    n  n_missing  pct_missing  n_unicos
0  12.OCIO_1   str  120         46    38.333333         3

Primeros valores no nulos:

4680                              En lugares abiertos y cerrados por igual
4682                              En lugares abiertos y cerrados por igual
4683                              En lugares abiertos y cerrados por igual
4684                              En lugares abiertos y cerrados por igual
4688                              En lugares abiertos y cerrados por igual
4689    Principalmente en casa o reuniones con amigos en espacios privados
4690    Principalmente en casa o reuniones con amigos en espacios privados
4691                              En lugares abiertos y cerrados por igual
4693                              En lugares abiertos y cerrados por igual
4694                              En lugares abiertos y cerrados por igual
4695                              En lugares abiertos y cerrados por igual
4696                              En lugares abiertos y cerrados por igual
4697                              En lugares abiertos y cerrados por igual
4698                              En lugares abiertos y cerrados por igual
4700                              En lugares abiertos y cerrados por igual
4701                              En lugares abiertos y cerrados por igual
4702                              En lugares abiertos y cerrados por igual
4703    Principalmente en casa o reuniones con amigos en espacios privados
4705                              En lugares abiertos y cerrados por igual
4707                              En lugares abiertos y cerrados por igual
4709                              En lugares abiertos y cerrados por igual
4710                              En lugares abiertos y cerrados por igual
4712                              En lugares abiertos y cerrados por igual
4715    Principalmente en casa o reuniones con amigos en espacios privados
4716    Principalmente en casa o reuniones con amigos en espacios privados
4717                              En lugares abiertos y cerrados por igual
4719                              En lugares abiertos y cerrados por igual
4720                              En lugares abiertos y cerrados por igual
4722                              En lugares abiertos y cerrados por igual
4724                              En lugares abiertos y cerrados por igual
4725                              En lugares abiertos y cerrados por igual
4726    Principalmente en casa o reuniones con amigos en espacios privados
4728                              En lugares abiertos y cerrados por igual
4730    Principalmente en casa o reuniones con amigos en espacios privados
4732                              En lugares abiertos y cerrados por igual
4734                              En lugares abiertos y cerrados por igual
4735    Principalmente en casa o reuniones con amigos en espacios privados
4736                              En lugares abiertos y cerrados por igual
4737                              En lugares abiertos y cerrados por igual
4738                              En lugares abiertos y cerrados por igual
4741    Principalmente en casa o reuniones con amigos en espacios privados
4742                              En lugares abiertos y cerrados por igual
4744                              En lugares abiertos y cerrados por igual
4745    Principalmente en casa o reuniones con amigos en espacios privados
4746                              En lugares abiertos y cerrados por igual
4747                              En lugares abiertos y cerrados por igual
4750                              En lugares abiertos y cerrados por igual
4751                              En lugares abiertos y cerrados por igual
4752                              En lugares abiertos y cerrados por igual
4753                              En lugares abiertos y cerrados por igual
4755                              En lugares abiertos y cerrados por igual
4757                              En lugares abiertos y cerrados por igual
4758                              En lugares abiertos y cerrados por igual
4759                              En lugares abiertos y cerrados por igual
4760                              En lugares abiertos y cerrados por igual
4761                              En lugares abiertos y cerrados por igual
4762                              En lugares abiertos y cerrados por igual
4763    Principalmente en casa o reuniones con amigos en espacios privados
4765                                               En casa y en cafeterías
4767                              En lugares abiertos y cerrados por igual
4770                              En lugares abiertos y cerrados por igual
4771    Principalmente en casa o reuniones con amigos en espacios privados
4772    Principalmente en casa o reuniones con amigos en espacios privados
4774    Principalmente en casa o reuniones con amigos en espacios privados
4778                              En lugares abiertos y cerrados por igual
4780                              En lugares abiertos y cerrados por igual
4781                              En lugares abiertos y cerrados por igual
4782    Principalmente en casa o reuniones con amigos en espacios privados
4783    Principalmente en casa o reuniones con amigos en espacios privados
4785    Principalmente en casa o reuniones con amigos en espacios privados
4786    Principalmente en casa o reuniones con amigos en espacios privados
4792                              En lugares abiertos y cerrados por igual
4798                              En lugares abiertos y cerrados por igual
4799    Principalmente en casa o reuniones con amigos en espacios privados
Name: 12.OCIO_1, dtype: str

Frecuencias (incluyendo NA):

12.OCIO_1
En lugares abiertos y cerrados por igual                              54
NaN                                                                   46
Principalmente en casa o reuniones con amigos en espacios privados    19
En casa y en cafeterías                                                1
Name: count, dtype: int64

           columna dtype    n  n_missing  pct_missing  n_unicos
0  13.TRANSPORTE_1   str  120         12         10.0         5

Primeros valores no nulos:

4680    Frecuente
4682    Frecuente
4684         Nula
4685         Nula
4687    Frecuente
4688    Frecuente
4689         Nula
4690         Nula
4692     Muy baja
4693    Frecuente
4694        Media
4695     Muy baja
4696    Frecuente
4697    Frecuente
4698         Nula
4699    Frecuente
4700         Baja
4701    Frecuente
4702    Frecuente
4703         Nula
4704         Baja
4705    Frecuente
4707    Frecuente
4708    Frecuente
4709         Nula
4710        Media
4711     Muy baja
4712         Nula
4713    Frecuente
4714     Muy baja
4715         Baja
4716        Media
4717    Frecuente
4718    Frecuente
4719         Baja
4720         Baja
4721    Frecuente
4723    Frecuente
4724    Frecuente
4725         Baja
4726    Frecuente
4727     Muy baja
4728    Frecuente
4729    Frecuente
4730         Nula
4731        Media
4732    Frecuente
4733    Frecuente
4734         Nula
4735    Frecuente
4736    Frecuente
4737    Frecuente
4738         Baja
4739         Nula
4741        Media
4742    Frecuente
4743         Baja
4744         Baja
4745    Frecuente
4746    Frecuente
4748    Frecuente
4749     Muy baja
4751         Nula
4752     Muy baja
4753    Frecuente
4754         Nula
4755    Frecuente
4756    Frecuente
4757    Frecuente
4758        Media
4759        Media
4760         Baja
4761    Frecuente
4762    Frecuente
4763    Frecuente
4764    Frecuente
4765    Frecuente
4766    Frecuente
4767     Muy baja
4768         Nula
4769    Frecuente
4770         Baja
4771     Muy baja
4772        Media
4773    Frecuente
4774    Frecuente
4775    Frecuente
4776    Frecuente
4777    Frecuente
4778    Frecuente
4779    Frecuente
4780    Frecuente
4781    Frecuente
4782        Media
4783    Frecuente
4784    Frecuente
4785    Frecuente
4787    Frecuente
4788    Frecuente
4789    Frecuente
4790         Nula
4791    Frecuente
4792     Muy baja
4793         Nula
4794    Frecuente
4795         Nula
4797         Baja
4798         Nula
Name: 13.TRANSPORTE_1, dtype: str

Frecuencias (incluyendo NA):

13.TRANSPORTE_1
Frecuente    59
Nula         18
NaN          12
Baja         12
Muy baja     10
Media         9
Name: count, dtype: int64

           columna dtype    n  n_missing  pct_missing  n_unicos
0  13.TRANSPORTE_2   str  120         33         27.5         5

Primeros valores no nulos:

4680         Baja
4682         Nula
4684         Nula
4685         Nula
4686         Nula
4687         Nula
4689         Nula
4690         Nula
4694     Muy baja
4695         Nula
4696         Nula
4697         Nula
4698         Nula
4700         Nula
4702         Nula
4703         Nula
4705         Nula
4707         Nula
4708         Nula
4709         Nula
4710         Nula
4712         Nula
4713         Nula
4714         Nula
4715         Nula
4720         Nula
4721         Nula
4722     Muy baja
4723         Nula
4724         Nula
4725         Nula
4726         Nula
4728         Nula
4729         Nula
4730         Nula
4731    Frecuente
4732         Nula
4734         Nula
4735    Frecuente
4736         Nula
4737         Nula
4739         Nula
4741         Nula
4742         Nula
4744         Baja
4745         Nula
4746         Nula
4748         Nula
4751         Nula
4752         Nula
4753         Nula
4754         Nula
4755         Nula
4756         Nula
4758         Nula
4759         Nula
4761         Nula
4762    Frecuente
4763         Nula
4764         Nula
4765         Nula
4766    Frecuente
4767         Nula
4768         Nula
4769     Muy baja
4771         Nula
4772         Nula
4773         Nula
4774        Media
4775         Nula
4779         Nula
4781         Nula
4782    Frecuente
4783         Nula
4784    Frecuente
4786         Nula
4788        Media
4789         Nula
4790         Nula
4791        Media
4792         Nula
4793         Nula
4794         Nula
4795         Nula
4797         Nula
4798         Nula
4799        Media
Name: 13.TRANSPORTE_2, dtype: str

Frecuencias (incluyendo NA):

13.TRANSPORTE_2
Nula         72
NaN          33
Frecuente     6
Media         4
Muy baja      3
Baja          2
Name: count, dtype: int64

           columna dtype    n  n_missing  pct_missing  n_unicos
0  13.TRANSPORTE_3   str  120         38    31.666667         4

Primeros valores no nulos:

4680        Baja
4681        Baja
4682       Media
4684        Baja
4685    Muy baja
4686    Muy baja
4687        Nula
4688       Media
4689    Muy baja
4690        Nula
4694    Muy baja
4695        Baja
4696        Nula
4697    Muy baja
4698    Muy baja
4699        Baja
4700        Baja
4702        Nula
4703    Muy baja
4705        Nula
4707        Baja
4709    Muy baja
4710    Muy baja
4712        Baja
4713    Muy baja
4714        Nula
4715        Nula
4720        Nula
4721        Nula
4723        Nula
4724        Nula
4725        Nula
4726        Nula
4728        Baja
4729        Nula
4730        Nula
4732       Media
4734        Nula
4736        Nula
4737        Nula
4739       Media
4741        Nula
4742        Nula
4746        Baja
4748        Nula
4751        Baja
4752    Muy baja
4753    Muy baja
4754        Nula
4755    Muy baja
4756       Media
4758        Nula
4759        Nula
4761        Nula
4762        Nula
4763        Nula
4764        Nula
4765        Nula
4766        Nula
4767    Muy baja
4769        Nula
4771        Baja
4772    Muy baja
4773        Nula
4774        Nula
4775        Nula
4777        Nula
4779        Nula
4781    Muy baja
4782        Nula
4783    Muy baja
4786        Nula
4788    Muy baja
4789        Nula
4790    Muy baja
4791    Muy baja
4792        Baja
4793        Nula
4794        Nula
4795    Muy baja
4797        Nula
4798        Nula
Name: 13.TRANSPORTE_3, dtype: str

Frecuencias (incluyendo NA):

13.TRANSPORTE_3
Nula        43
NaN         38
Muy baja    21
Baja        13
Media        5
Name: count, dtype: int64

           columna dtype    n  n_missing  pct_missing  n_unicos
0  13.TRANSPORTE_4   str  120         33         27.5         5

Primeros valores no nulos:

4680     Muy baja
4681         Baja
4682    Frecuente
4684    Frecuente
4685         Nula
4686         Nula
4687         Nula
4689    Frecuente
4690         Nula
4694         Baja
4695         Baja
4696         Nula
4697         Nula
4698         Nula
4699         Baja
4700         Baja
4702     Muy baja
4703         Baja
4705         Nula
4707         Nula
4708    Frecuente
4709         Nula
4710         Nula
4712        Media
4713         Baja
4714     Muy baja
4715     Muy baja
4718        Media
4720         Nula
4721     Muy baja
4722     Muy baja
4723         Baja
4724         Nula
4725     Muy baja
4726         Nula
4728         Nula
4729         Nula
4730         Nula
4732        Media
4734     Muy baja
4736         Nula
4737         Nula
4739        Media
4741     Muy baja
4742         Nula
4744         Baja
4745         Nula
4746         Baja
4748         Nula
4751         Nula
4752         Nula
4753     Muy baja
4754    Frecuente
4755     Muy baja
4756         Baja
4758         Nula
4759         Nula
4761         Nula
4762     Muy baja
4763         Nula
4764         Nula
4765     Muy baja
4766     Muy baja
4767     Muy baja
4768         Nula
4769         Nula
4771        Media
4772         Nula
4773         Nula
4774         Nula
4775         Nula
4776         Baja
4777         Nula
4779     Muy baja
4781         Nula
4782         Nula
4783     Muy baja
4786         Nula
4788     Muy baja
4789         Nula
4790         Baja
4791     Muy baja
4792        Media
4793         Nula
4794         Nula
4795    Frecuente
4797         Nula
Name: 13.TRANSPORTE_4, dtype: str

Frecuencias (incluyendo NA):

13.TRANSPORTE_4
Nula         43
NaN          33
Muy baja     19
Baja         13
Frecuente     6
Media         6
Name: count, dtype: int64

           columna dtype    n  n_missing  pct_missing  n_unicos
0  13.TRANSPORTE_5   str  120         31    25.833333         5

Primeros valores no nulos:

4680         Baja
4681    Frecuente
4682        Media
4684    Frecuente
4685        Media
4686     Muy baja
4687         Nula
4688         Baja
4690         Nula
4693     Muy baja
4694        Media
4695         Baja
4696         Nula
4697         Nula
4698         Nula
4699         Baja
4700        Media
4702         Nula
4703     Muy baja
4704         Baja
4705         Nula
4707     Muy baja
4708        Media
4709         Baja
4710         Nula
4712        Media
4713         Baja
4714     Muy baja
4715         Nula
4720         Nula
4721     Muy baja
4723    Frecuente
4724         Nula
4725         Nula
4726         Nula
4727     Muy baja
4728         Nula
4729         Baja
4730         Nula
4732        Media
4734         Baja
4736     Muy baja
4737     Muy baja
4739     Muy baja
4741     Muy baja
4742         Nula
4745         Nula
4746         Baja
4748         Nula
4750        Media
4751    Frecuente
4752     Muy baja
4753         Nula
4754    Frecuente
4755         Nula
4756         Nula
4758     Muy baja
4759     Muy baja
4761         Nula
4762     Muy baja
4763         Nula
4764         Nula
4765    Frecuente
4766         Nula
4768        Media
4769     Muy baja
4771        Media
4772         Nula
4773         Nula
4774         Nula
4775         Nula
4776         Baja
4777         Nula
4779         Nula
4781     Muy baja
4782         Baja
4783     Muy baja
4786         Nula
4787         Baja
4788         Nula
4789         Nula
4790         Baja
4791         Nula
4792    Frecuente
4793     Muy baja
4794     Muy baja
4795    Frecuente
4797         Baja
4798     Muy baja
Name: 13.TRANSPORTE_5, dtype: str

Frecuencias (incluyendo NA):

13.TRANSPORTE_5
Nula         35
NaN          31
Muy baja     21
Baja         15
Media        10
Frecuente     8
Name: count, dtype: int64

           columna dtype    n  n_missing  pct_missing  n_unicos
0  13.TRANSPORTE_6   str  120         36         30.0         5

Primeros valores no nulos:

4681         Baja
4684         Nula
4685         Baja
4686     Muy baja
4687         Nula
4688         Baja
4689         Nula
4690         Nula
4694        Media
4695         Nula
4696         Nula
4697     Muy baja
4698         Nula
4700         Nula
4702         Nula
4703         Nula
4705         Nula
4707         Baja
4708         Nula
4709         Nula
4710         Nula
4712         Nula
4713         Nula
4714         Nula
4715         Nula
4719         Nula
4720         Nula
4721         Baja
4723         Nula
4724        Media
4725         Nula
4726         Baja
4728         Nula
4729        Media
4730    Frecuente
4732         Nula
4734         Nula
4736     Muy baja
4737     Muy baja
4739         Baja
4741         Nula
4742         Nula
4745         Baja
4746     Muy baja
4748         Nula
4750         Baja
4751        Media
4752         Nula
4753     Muy baja
4754         Nula
4755     Muy baja
4756     Muy baja
4758         Nula
4759         Nula
4761         Nula
4762         Nula
4763         Nula
4764         Nula
4765         Baja
4766         Nula
4767         Nula
4768     Muy baja
4769         Baja
4771         Baja
4772         Nula
4773         Nula
4774         Nula
4775     Muy baja
4777         Nula
4779         Nula
4781     Muy baja
4782         Nula
4783         Nula
4786         Nula
4788         Nula
4789         Nula
4790         Nula
4791         Nula
4792         Nula
4793         Nula
4794         Nula
4795         Nula
4797         Nula
4798         Nula
Name: 13.TRANSPORTE_6, dtype: str

Frecuencias (incluyendo NA):

13.TRANSPORTE_6
Nula         56
NaN          36
Baja         12
Muy baja     11
Media         4
Frecuente     1
Name: count, dtype: int64

           columna dtype    n  n_missing  pct_missing  n_unicos
0  13.TRANSPORTE_7   str  120         17    14.166667         5

Primeros valores no nulos:

4680    Frecuente
4681    Frecuente
4682         Nula
4683    Frecuente
4684         Nula
4685    Frecuente
4686     Muy baja
4687    Frecuente
4689     Muy baja
4690    Frecuente
4691    Frecuente
4692     Muy baja
4694    Frecuente
4695    Frecuente
4696        Media
4697        Media
4698     Muy baja
4700    Frecuente
4702         Baja
4703         Baja
4704    Frecuente
4705         Baja
4707         Baja
4708    Frecuente
4709    Frecuente
4710    Frecuente
4712        Media
4713        Media
4714     Muy baja
4715        Media
4716    Frecuente
4718        Media
4719         Baja
4720    Frecuente
4721         Baja
4723    Frecuente
4724     Muy baja
4725    Frecuente
4726     Muy baja
4727     Muy baja
4728        Media
4729    Frecuente
4730    Frecuente
4732    Frecuente
4734        Media
4736     Muy baja
4737     Muy baja
4738        Media
4739    Frecuente
4740         Baja
4741    Frecuente
4742        Media
4745        Media
4746         Baja
4747    Frecuente
4748    Frecuente
4749     Muy baja
4750    Frecuente
4751    Frecuente
4752    Frecuente
4753    Frecuente
4754         Baja
4755    Frecuente
4756         Baja
4757        Media
4758        Media
4759        Media
4761         Nula
4762        Media
4763         Baja
4764     Muy baja
4765    Frecuente
4766        Media
4767    Frecuente
4768    Frecuente
4769    Frecuente
4770    Frecuente
4771     Muy baja
4772    Frecuente
4773    Frecuente
4774         Baja
4775        Media
4776         Baja
4777        Media
4779         Baja
4780        Media
4781         Baja
4782    Frecuente
4783    Frecuente
4784    Frecuente
4785        Media
4786         Nula
4788     Muy baja
4789         Nula
4790         Baja
4791     Muy baja
4792    Frecuente
4793    Frecuente
4794         Nula
4795    Frecuente
4797        Media
4798     Muy baja
4799    Frecuente
Name: 13.TRANSPORTE_7, dtype: str

Frecuencias (incluyendo NA):

13.TRANSPORTE_7
Frecuente    44
Media        21
NaN          17
Muy baja     16
Baja         16
Nula          6
Name: count, dtype: int64

           columna dtype    n  n_missing  pct_missing  n_unicos
0  14.EXTRANJERO_1   str  120          6          5.0        20

Primeros valores no nulos:

4680                     NO
4681                     No
4682                     NO
4683                     no
4684                     no
4685                     NO
4686                     NO
4687                     No
4688                     NO
4689                     No
4690                     No
4691                     No
4692                     No
4693                     No
4694                    No
4695                     No
4696                     No
4697                     No
4698                     No
4699                     No
4700          SI. Marruecos
4701                     No
4702                     No
4703                     No
4704                     No
4705                     No
4706                     No
4707                     No
4708                     No
4709                     No
4710           Si.Marruecos
4711                     No
4712                     No
4713             Sí. España
4714                     No
4715                     si
4716                     NO
4717                     No
4718                     No
4719    Si. Italia/Portugal
4720                     No
4721           Sí. Budapest
4722                     No
4723                     No
4724                     No
4725                     NO
4726                     No
4727                     No
4728                     No
4729                     No
4730               Portugal
4731                     No
4732              Si. París
4733                     No
4734                     Si
4735                     No
4736                     No
4737                     No
4738                     NO
4739           Si. Portugal
4740                     No
4741                     no
4742          Si. Alemania.
4743                     No
4744                     No
4745                     No
4746                     No
4747                     No
4748                     No
4749                     NO
4750                     No
4751                     No
4752                     No
4753                     No
4754           SI Marruecos
4755                     No
4757                     No
4758           Si/Portugal
4759           Si/Portugal
4760                     no
4761                     No
4762                     no
4763                     NO
4764                     No
4765                     No
4766                     No
4768                     No
4769                     No
4770                     No
4771                     No
4772                     No
4773                     No
4774                     No
4775                     NO
4776                     No
4777                     No
4778                     No
4779                     No
4781                     No
4784                     NO
4785                     No
4786                     No
4787             Si Londres
4788            Si! Holanda
4789                Francia
4790                     NO
4791            Si! Holanda
4792                    No
4793                     No
4795                     NO
4796                     No
4797                     No
4798                     Si
4799                     NO
Name: 14.EXTRANJERO_1, dtype: str

Frecuencias (incluyendo NA):

14.EXTRANJERO_1
No                     73
NO                     15
NaN                     6
no                      5
No                      2
Si                      2
Si/Portugal             2
Si! Holanda             2
SI. Marruecos           1
Si.Marruecos            1
Sí. España              1
si                      1
Si. Italia/Portugal     1
Sí. Budapest            1
Portugal                1
Si. París               1
Si. Portugal            1
Si. Alemania.           1
SI Marruecos            1
Si Londres              1
Francia                 1
Name: count, dtype: int64

                        columna dtype    n  n_missing  pct_missing  n_unicos
0  15.DESPLAZAMIENTO-NACIONAL_1   str  120         46    38.333333         3

Primeros valores no nulos:

4681    No he salido de mi comunidad
4682                         Córdoba
4683    No he salido de mi comunidad
4684    No he salido de mi comunidad
4686    No he salido de mi comunidad
4687    No he salido de mi comunidad
4689    No he salido de mi comunidad
4690    No he salido de mi comunidad
4692    No he salido de mi comunidad
4693    No he salido de mi comunidad
4695    No he salido de mi comunidad
4696    No he salido de mi comunidad
4698    No he salido de mi comunidad
4699    No he salido de mi comunidad
4700    No he salido de mi comunidad
4701    No he salido de mi comunidad
4702    No he salido de mi comunidad
4704    No he salido de mi comunidad
4705    No he salido de mi comunidad
4706    No he salido de mi comunidad
4707    No he salido de mi comunidad
4710                   Sierra nevada
4711    No he salido de mi comunidad
4715    No he salido de mi comunidad
4716    No he salido de mi comunidad
4718    No he salido de mi comunidad
4720    No he salido de mi comunidad
4721    No he salido de mi comunidad
4723    No he salido de mi comunidad
4724    No he salido de mi comunidad
4725    No he salido de mi comunidad
4726    No he salido de mi comunidad
4727    No he salido de mi comunidad
4728    No he salido de mi comunidad
4729    No he salido de mi comunidad
4730    No he salido de mi comunidad
4733    No he salido de mi comunidad
4735    No he salido de mi comunidad
4736    No he salido de mi comunidad
4737    No he salido de mi comunidad
4738    No he salido de mi comunidad
4739    No he salido de mi comunidad
4741    No he salido de mi comunidad
4745    No he salido de mi comunidad
4747    No he salido de mi comunidad
4748    No he salido de mi comunidad
4751    No he salido de mi comunidad
4752    No he salido de mi comunidad
4753    No he salido de mi comunidad
4754    No he salido de mi comunidad
4755    No he salido de mi comunidad
4758    No he salido de mi comunidad
4759    No he salido de mi comunidad
4761    No he salido de mi comunidad
4762    No he salido de mi comunidad
4763    No he salido de mi comunidad
4764    No he salido de mi comunidad
4767    No he salido de mi comunidad
4769    No he salido de mi comunidad
4770    No he salido de mi comunidad
4771    No he salido de mi comunidad
4772    No he salido de mi comunidad
4774    No he salido de mi comunidad
4778    No he salido de mi comunidad
4780    No he salido de mi comunidad
4781    No he salido de mi comunidad
4786    No he salido de mi comunidad
4787    No he salido de mi comunidad
4788    No he salido de mi comunidad
4789    No he salido de mi comunidad
4791    No he salido de mi comunidad
4792    No he salido de mi comunidad
4795    No he salido de mi comunidad
4799    No he salido de mi comunidad
Name: 15.DESPLAZAMIENTO-NACIONAL_1, dtype: str

Frecuencias (incluyendo NA):

15.DESPLAZAMIENTO-NACIONAL_1
No he salido de mi comunidad    72
NaN                             46
Córdoba                          1
Sierra nevada                    1
Name: count, dtype: int64

In [53]:
# P1
print(f"---P1---")
print(f"{df_trabajo.loc[df_trabajo["1.CPBARRIO-ANTES_1"].str.len() < 5, "1.CPBARRIO-ANTES_1"]}")
print(f"{df_trabajo.loc[df_trabajo["1.CPBARRIO-ANTES_1"].isnull(), "1.CPBARRIO-ANTES_1"]}")
print("Vemos que tenemos una columna que es el código postal " 
      "y el tipo de columna es un string. A pesar de ser un valor " 
      "numérico, en España se mantiene los 0 a la izquierda, por " 
      "lo que lo mantenemos. Además hay un valor faltante y "
      "también nos aseguraremos que el código postal tenga 5 " 
      "dígitos.")
df_trabajo["1.cp_barrio_antes_1"] = df_trabajo["1.CPBARRIO-ANTES_1"].astype(str).str.extract(r"(\0?\d+)")[0].str.zfill(5)
registrar_auditoria("1.CPBARRIO-ANTES_1",
                    "Valores nulos, el código postal necesita "
                    "5 dígitos, y hay valores que no lo cumplen.",
                    "Crear una nueva columna y rellenar con 0 "
                    "a la izquierda y mas adelante manejaremos los "
                    "nulos",
                    "1.cp_barrio_antes_1")

---P1---
4713    1050
4777    5418
Name: 1.CPBARRIO-ANTES_1, dtype: object
4719    NaN
Name: 1.CPBARRIO-ANTES_1, dtype: object
Vemos que tenemos una columna que es el código postal y el tipo de columna es un string. A pesar de ser un valor numérico, en España se mantiene los 0 a la izquierda, por lo que lo mantenemos. Además hay un valor faltante y también nos aseguraremos que el código postal tenga 5 dígitos.

## Bloque P2 — Hábitos de convivencia y sociales **DURANTE** el confinamiento

Preguntas:

- **16 y 16.1**: código postal y barrio durante el confinamiento.
- **17 y 18**: tipo de domicilio y afluencia.
- **19 y 20**: número y edades de convivientes.
- **21**: mascotas.
- **22**: ámbito y forma de ejercer la profesión.
- **23**: lugar de trabajo.
- **24**: mes de inicio de medidas de seguridad.
- **25**: frecuencia de medidas de seguridad.

### Sugerencias específicas

- Compara P1 frente a P2 cuando tenga sentido: domicilio, afluencia, convivencia, etc.
- En **21** y **22** puede haber problemas de coherencia entre varias marcas.
- En **24** y **25** hay estructura **ordinal**: decide si conviene conservar texto, codificar ordinalmente o ambas cosas.

In [ ]:
preguntas_p2 = ["16", "16.1", "17", "18", "19", "20", "21", "22", "23", "24", "25"]
cols_p2 = columnas_por_bloque(df_trabajo, preguntas_p2)

display(auditoria[auditoria["columna_original"].isin(cols_p2)])

In [ ]:
# TODO P2:
# Analiza y limpia las columnas de cols_p2.
# Para preguntas de tipo ordinal, justifica la codificación elegida.

## Bloque P3 — Estado de salud y hábitos personales

Preguntas:

- **26**: tabaquismo.
- **27**: alcohol.
- **28**: bebidas estimulantes.
- **29, 30, 31**: medicación/tratamientos.
- **32**: consumo de productos.
- **33**: estado de salud general.
- **34, 35, 36, 37, 38, 39**: grupos de enfermedades.
- **40 y 40.1**: EPOC y condiciones de riesgo.

### Sugerencias específicas

- En **26** hay mezcla de categorías que parecen tener orden y otras que no.
- En **28** y **32** hay tablas de frecuencia: trata la ordinalidad con cuidado.
- En **34–39** hay muchas columnas binarias/ternarias: revisa **consistencia** y unifica codificación.
- En **40.1** puede haber multirrespuesta y posible contradicción entre `No` y otra condición marcada.

In [ ]:
preguntas_p3 = ["26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "40.1"]
cols_p3 = columnas_por_bloque(df_trabajo, preguntas_p3)

display(auditoria[auditoria["columna_original"].isin(cols_p3)])

In [ ]:
# TODO P3:
# 1) inspecciona cols_p3;
# 2) crea, si lo consideras útil, variables agregadas:
#    - número de enfermedades metabólicas
#    - número de alergias
#    - número de patologías respiratorias
#    - indicador global de comorbilidad
# 3) documenta todo en auditoria.

## Bloque P4 — Estado de salud durante el confinamiento

Preguntas:

- **41**: estado de salud en los últimos meses.
- **42, 43, 44, 45**: ingreso hospitalario, visitas al hospital y otras patologías.
- **46**: sintomatología.

### Sugerencias específicas

- En **41** hay una variable ordinal clara.
- En **42**, **44** y **45** puede haber mezcla entre sí/no y texto libre en “otro”.
- En **46** tendrás varias columnas binarias: revisa si todas usan la misma codificación y crea variables resumen si están justificadas.

In [ ]:
preguntas_p4 = ["41", "42", "43", "44", "45", "46"]
cols_p4 = columnas_por_bloque(df_trabajo, preguntas_p4)

display(auditoria[auditoria["columna_original"].isin(cols_p4)])

In [ ]:
# TODO P4:
# Limpia cols_p4 y, si procede, crea variables derivadas:
# - numero_sintomas
# - sintoma_respiratorio
# - sintoma_digestivo
# - sintoma_neurologico
# etc.

## Bloque P5 — Información referente a vacunas y COVID

Preguntas:

- **47**: vacunas/enfermedades previas.
- **48**: convivencia con positivo COVID.
- **49**: sospecha de COVID.
- **50**: prueba PCR.
- **51**: anticuerpos.

### Sugerencias específicas

- En **47** vuelve a aparecer estructura multicolumna/ternaria.
- En **50** y **51** conviene revisar si la variable debe quedarse como texto categórico o si puede descomponerse en indicadores más simples.
- Piensa qué variable podría servir como **objetivo** o como **variable de interés clínica**.

In [ ]:
preguntas_p5 = ["47", "48", "49", "50", "51"]
cols_p5 = columnas_por_bloque(df_trabajo, preguntas_p5)

display(auditoria[auditoria["columna_original"].isin(cols_p5)])

In [ ]:
# TODO P5:
# Limpia cols_p5 y decide si conviene crear:
# - covid_pcr_realizada
# - covid_pcr_positiva
# - covid_anticuerpos
# - covid_sospecha_binaria
# etc.

# 7. Tratamiento de valores faltantes

Tras la limpieza básica, debes estudiar **qué columnas tienen faltantes** y decidir, de forma justificada, qué hacer en cada caso.

## Debes incluir ejemplos de:

1. **Eliminación** de filas o columnas, si la justificas.
2. **Imputación simple**:
   - media o mediana para numéricas,
   - moda para categóricas.
3. **Al menos una imputación más elaborada** o una estrategia razonada basada en otras columnas, si el caso lo merece.

## No se acepta

- rellenar todo “a ojo”;
- usar siempre la misma estrategia para todas las columnas;
- imputar sin explicar por qué.

In [ ]:
# TODO:
# crea una tabla con el porcentaje de faltantes y decide qué columnas requieren tratamiento específico
# missing = ...
# display(missing)

In [ ]:
# TODO:
# escribe aquí tus imputaciones justificadas
# ejemplos posibles:
# - imputación de edad por mediana
# - imputación de peso/talla tras detectar outliers
# - imputación de una categoría por moda
# - no imputar y mantener NaN si la ausencia es informativa

# 8. Detección y tratamiento de outliers

Debes aplicar este análisis, al menos, a las variables numéricas que finalmente consideres relevantes.

## Variables candidatas típicas

- edad,
- peso,
- talla,
- número de convivientes,
- resúmenes numéricos que extraigas de otras preguntas,
- IMC.

## Lo que debes hacer

1. Convertir la columna a numérica si es necesario.
2. Visualizar con histogramas y boxplots.
3. Detectar candidatos a outlier con **IQR** o **z-score**.
4. Decidir si son:
   - error de captura,
   - caso extremo real,
   - falta de unidad consistente,
   - dato que debe conservarse.
5. Aplicar una acción justificada:
   - corregir,
   - imputar,
   - marcar,
   - transformar,
   - eliminar (solo si se justifica muy bien).

In [ ]:
# TODO:
# elige aquí tus variables numéricas ya limpiadas y analízalas
# ejemplo:
# ver_numerica(df_trabajo, "3.EDAD_1")

In [ ]:
# TODO:
# implementa al menos una detección de outliers con IQR o z-score

# 9. Transformación de datos

En esta parte debes aplicar **transformaciones con sentido**.

## Obligatorio

### 9.1. Creación de nuevas variables
Debes crear varias variables derivadas. Algunas candidatas son:

- `imc` a partir de peso y talla;
- número de convivientes;
- número de mascotas;
- número de enfermedades por bloque;
- número de síntomas;
- indicadores binarios de riesgo.

### 9.2. Codificación de variables categóricas
Debes usar, cuando corresponda:

- **One-Hot Encoding** para variables nominales;
- **Ordinal Encoding** para variables con orden lógico;
- **Label Encoding** solo si justificas por qué no introduces una jerarquía artificial.

### 9.3. Escalado/normalización
Aplica y compara, al menos sobre algunas variables numéricas limpias:

- Min–Max,
- Z-score,
- o normalización decimal.

### 9.4. Discretización
Discretiza, al menos, una variable continua de forma justificada:
por ejemplo edad, IMC o número de convivientes.

In [ ]:
# TODO:
# crea aquí tus variables derivadas
# Ejemplos posibles:
# df_trabajo["imc"] = ...
# df_trabajo["numero_sintomas"] = ...
# df_trabajo["numero_enfermedades_metabolicas"] = ...

In [ ]:
# TODO:
# aplica aquí codificación de variables categóricas elegidas
# y justifica por qué eliges one-hot, ordinal o label

In [ ]:
# TODO:
# aplica aquí algún escalado a varias variables numéricas limpias
# Puedes crear un dataframe aparte con las variables escaladas

In [ ]:
# TODO:
# discretiza aquí al menos una variable continua
# Ejemplos: edad por rangos, IMC por categorías, etc.

# 10. Reducción de datos

Debes construir una versión del dataset adecuada para un análisis posterior o para un modelo de aprendizaje automático.

## Objetivo

Crear `df_modelo` con aproximadamente **15 variables útiles**.

## Requisitos

1. No basta con elegir 15 columnas “porque sí”.
2. Debes justificar por qué eliminas:
   - columnas redundantes,
   - columnas con demasiados faltantes,
   - columnas excesivamente libres o difíciles de usar,
   - columnas que duplican información.
3. Puedes conservar:
   - columnas limpias originales,
   - variables derivadas,
   - columnas codificadas.
4. Si quieres, puedes apoyar la selección con:
   - sentido del dominio,
   - baja cardinalidad,
   - relación con el objetivo,
   - correlaciones,
   - variabilidad,
   - proporción de faltantes.

In [ ]:
# TODO:
# define aquí df_limpio cuando hayas terminado la limpieza principal
# Sugerencia: usa una selección explícita de columnas limpias
# df_limpio = df_trabajo[[ ... ]].copy()

In [ ]:
# TODO:
# define aquí df_modelo con ~15 variables útiles
# df_modelo = ...

In [ ]:
# TODO:
# justifica aquí tu selección de variables
# Puedes crear una tabla con:
# - variable
# - motivo_para_conservarla
# - tipo
# - tratamiento_aplicado

# 11. Guardado de resultados

Cuando termines, guarda:

- la tabla de auditoría;
- el dataset limpio;
- el dataset reducido.

In [ ]:
# TODO:
# auditoria.to_excel(carpeta / f"Auditoria_EncuestaCOVID_{codigo:02d}.xlsx", index=False)
# df_limpio.to_excel(carpeta / f"DatosEncuestaCOVID_limpio_{codigo:02d}.xlsx", index=False)
# df_modelo.to_excel(carpeta / f"DatosEncuestaCOVID_modelo_{codigo:02d}.xlsx", index=False)

# 12. Checklist final antes de entregar

Comprueba que tu notebook:

- carga solo tus 120 filas;
- mantiene una copia cruda (`df_raw`);
- contiene una auditoría **columna a columna**;
- detecta faltantes, inconsistencias y outliers;
- limpia y transforma con código;
- crea variables derivadas;
- aplica alguna codificación;
- aplica alguna normalización o discretización;
- construye `df_limpio`;
- construye `df_modelo`;
- guarda los resultados.

## Nota importante

El número real de columnas del XLSX debe comprobarse con `df.shape` y `df.info()`.  
No asumas el número de columnas sin verificarlo en tu fichero.